### ISSUE TITLE
CE Wizard is not showing fluidcontent elements

### ISSUE THREAD

**Issue by twirsing** [FluidTYPO3/fluidcontent#134]
Since Version 4.0.0 the content element wizard is not showing my custom elements, not even the tab. 
As far as I can see 

```
$cache->set('pageTsConfig', $pageTsConfig, array(), 806400);
```

in fluidcontent/Classes/Service/ConfigurationService.php:148` set correctly (the debugger shows all my items in the array) but eventually not honored by the wizard.

I am using:
typo3 6.1.8-dev
flux 7.0.0

**Comment by MoppieMop** [comment]
Can you please give more details, how to check for wrong configuration? How exactly can I check for the common problems?
How can I see syntax errors or invalid characters, in my TSConfig all my flux configs are shown. Is this a sign that my config is ok?
The flux ext_localconf is present in the cached localconf, I do not use allowed/deniedContentTypes and I am admin. What else could be the reason, that my custom fluidcontent is not shown?

**Comment by NamelessCoder** [comment]
@MoppieMop The [builder](https://github.com/FluidTYPO3/builder) extension has a backend module and CLI command that lets you validate the syntax of your Fluid templates against your current ViewHelper versions. It will report any invalid arguments as well as standard syntax issues.
