### ISSUE TITLE
Column: Invalid value ("18181") in nested FCE

### ISSUE THREAD

**Issue by coding46** [FluidTYPO3/fluidcontent#185]
If one creates a FCE with a grid as container for other (f)ces and puts these (f)ces into the container grid, the backend column select field of this element shows the value 'Invalid value ("18181")'.

This happens for combinations of FCE in FCE, FCC-element in FCE and all other kinds of contents one might put into the container.

Frontend rendering is correct, so it seems to be a presentational only issue.

Tested in combinations of:
- current TER versions of flux, fluidcontent
- latest github-dev commits of flux, fluidcontent, fluidcontent_core 

Confirmed by more than one user in support chat (29.09.2014 16:38 - 16:47)

**Comment by fnagel** [comment]
Does this still work? I always see that "18181 invalid" notice in my colPos select.

**Comment by fnagel** [comment]
Ahh ok,  I'm not using EXT:fluid_pages so this doesn't work for me. Any other option to get rid of this?

**Comment by NamelessCoder** [comment]
There is no option to get rid of this one without Fluidpages. It's all about how `backend_layout` and `DataProvider` works - basically, this pattern was created in a way that the providers become mutually exclusive and singular in nature. As soon as you change which one applies, all others stop working. In addition, the value has to be delivered in a special way that it doesn't cause a content column to be rendered in the page module (any ways you have of manually adding the value causes such a column to be rendered).

So we can deliver this value very easily and without conflicts with fluidpages which already has a backend layout integration that must be selected for fluidpages to deliver the layout. But the only way to achieve the same for pure Flux would be to provide a similar page-level backend layout feature as part of Flux - and that's simply not a route we ever want to take.

This situation is much less than ideal. I did what I could back then to push, nudge, shove and prod this in the right direction (e.g. make these providers NOT mutually exclusive!) but was unsuccessful. The current implementation was designed by and for Gridelements and did not take others into consideration.

**Comment by fnagel** [comment]
Ok, thanks for the answer. No need to invest more time here.

FYI: It was (!) possible to just add the 18181 as an item to a BackendLayout configuration -- as long as the row and col configuration excluded that row. Sadly something must have changed in TYPO3 as the col is shown regardless of the row / cols config since a few version.

**Comment by NamelessCoder** [comment]
> FYI: It was (!) possible to just add the 18181 as an item to a BackendLayout configuration -- as long as the row and col configuration excluded that row.

Yes, this trick used to work - unfortunately that door is now closed so we can't even provide a workaround now. Technically speaking it would be a bug, too. ;)

Will leave this as-is, fully aware it's not ideal but so far unable to push the TYPO3 core in a positive direction in this area (still trying, though).

**Comment by typo3ua** [comment]
**SOLUTION**
Add to "Backend Layouts" one rowCount with name = FCE and colPos = 18181
```
mod {
    web_layout {
        BackendLayouts {
            default_1Column {
                title = Default 3 Column
                config {
                    backend_layout {
                        colCount = 6
                        rowCount = 4
                        rows {
                            [...]
                            5 {
                                columns {
                                    1 {
                                        name = FCE
                                        colPos = 18181
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
