### ISSUE TITLE
[BUG] File link via RTE does not add a reference in filelist

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/fluidcontent#197]
Adding a link to a file in normal content element via RTE adds a reference in filelist.
The same done with a RTE in fluidcontent elements does not add this reference.

Is this a fluidcontent or flux bug?

**Comment by ste101** [comment]
Any news about this issue?

**Comment by NamelessCoder** [comment]
Use TypoScript `plugin.tx_flux.settings.flexform.rteDefaults` or manually define `defaultExtras=""` on your `flux:form`. The syntax documentation can be found in the official TYPO3 documentation (do a search for defaultExtras + RTE).

**Comment by ste101** [comment]
Unfortunatelly it seams that I'm to dumb to find the needed informations.
I think it RTE via flux should have the same default configuration than the RTE within standard CEs

**Comment by ste101** [comment]
Links within the RTE to internal sites are also wrong. The links get renderd absolute with the domain name you are logged in into the backend.
Please  Please Please Please Please Please Please Please Please Please Please  tell me a working RTE configuration or the link where I can find the information. I am to dumb.

Thanks
Stephan

**Comment by ste101** [comment]
Is this the right link:
http://docs.typo3.org/typo3cms/CoreApiReference/Rte/Transformations/Overview/Index.html

If so links should be converted with this code: ```defaultExtras="richtext:rte_transform[mode=ts_css]"``` but it does not.

**Comment by bjo3rnf** [comment]
This works for me: ``defaultExtras="richtext:rte_transform[flag=rte_enabled|mode=ts_css]"``
