### ISSUE TITLE
fluidcontent and languages: general question

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/fluidcontent#203]
a general question:

is it possible to use fluidcontent and fluidpage for a one tree multi language page?

are there any restrictions?

are there issues with workspaces?

**Comment by NamelessCoder** [comment]
That's a very broad question.

1. Yes, you can use fluidcontent and fluidpages selectively. Fluidpages has a toggle that lets you switch to manual inclusion of TS and fluidcontent's elements can be controlled via pageTSconfig just like any other content types.
2. You'll need to define what you mean by "restrictions" if the other replies here don't answer that question.
3. See https://github.com/FluidTYPO3/flux/issues/627
