### ISSUE TITLE
Unset templates for a specific tree branch

### ISSUE THREAD

**Issue by InvisibleKind** [FluidTYPO3/fluidcontent#204]
Hi and Merry Xmas =)

This is rather a question, than an issue: is there a possibility to disable custom CEs for a specific branch?

I've tried 2 cases: disable for a sub-branch and disable for a root-page.

Sub-branch disabling was useless. I've created a TS template record on a sub-branch, where I've disabled complete `view` section of my provider extension by `plugin.tx_myext.view >` and ensured with `TypoScript Object Browser`, that view is no longer set, but still page and content templates were there.

So, I've tried to create different tree root with different root TS template (which didn't include any TS from my provider extension) and it worked for page templates, but still content templates were on a "New CE Wizard Tab".

What am I doing wrong here?

flux 7.1.2
fluidpages 3.1.2
fluidcontent 4.1.1

The reference to this issue is a [StackOverflow comment](http://stackoverflow.com/questions/27400964/disable-fluidtypo3-page-template-and-or-content-elements/27657857#comment43734001_27657857)

**Comment by NamelessCoder** [comment]
Hi @InvisibleKind - would you mind recreating this issue in Flux's issue list and if you can, set the "Milestone" for the issue to "7.2". We'll need this feature provided by Flux so that any implementer can use it as well! Thanks :)

**Comment by InvisibleKind** [comment]
@NamelessCoder, done: https://github.com/FluidTYPO3/flux/issues/747
Unfortunately, I don't have rights to set a milestone, so, please, update it :)
