### ISSUE TITLE
way to change typoscript in fluidcontent template?

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/fluidcontent#210]
hi,

i search for a possibility to change the wrap of the standard content element headline only for a single fce.
For example: The standard headline is generated in H4 (content.defaultHeaderType = 4), but i want a H3.

is there a possibility? 
can i use typoscript in fluidcontent?

**Comment by cedricziel** [comment]
If you use the css_styled_content generated headline, this would be done va typoscript..

**Comment by blueamerican** [comment]
yes. the question is: can i use a content-specific typoscript in the content template?

**Comment by cedricziel** [comment]
The only way i can imagine is via the TCEFORM object in pageTSConfig; this way you can preset values for your backend on specific ctypes and with conditions.

I'll close this issue, as it is not directly related with fluidcontent, but rather with core behaviour; please post back how you did it.

**Comment by blueamerican** [comment]
i tried
```
lib.stdheader >
lib.stdheader = CASE
lib.stdheader {

key.field = tx_fed_fcefile

my_provider_ext:TeaserBildTest.html = TEXT
my_provider_ext:TeaserBildTest.html.field = header
my_provider_ext:TeaserBildTest.html.wrap = <h2 style="color: green;">|</h2>
  
default = TEXT
default.field = header
default.wrap = <h1>|</h1>
}
```
but it doesn't work.

maybe the : 
in my_provider_ext:TeaserBildTest.html is the reason.

if i ask for Ctype i only get fluidcontent_content. her i can't distinguish between different FCE's

**Comment by blueamerican** [comment]
hello cedric,

can you please reopen this issue?
i think it is a fluidcontent and not a core issue.

in tt_content i can't distinguish between my fce's.

or is there a possibility to fill a db field with this information manually?
