### ISSUE TITLE
allowedContentTypes doesn't work when try add new CE behind existing CE

### ISSUE THREAD

**Issue by rastocs2** [FluidTYPO3/fluidcontent#211]
problem is here:
![img1](https://cloud.githubusercontent.com/assets/5691082/6017063/5449cf6c-ab8a-11e4-9302-02ab8abd722e.png)
because then calling function getGrid read grid from existing CE and not from parent (that it's wrong):
![img2](https://cloud.githubusercontent.com/assets/5691082/6017118/f0d071c4-ab8a-11e4-9e95-eee8535c7542.png)

same problem is in Flux

**Comment by NamelessCoder** [comment]
Thanks for reporting!
