### ISSUE TITLE
No Default.html template error

### ISSUE THREAD

**Issue by GuidoJansen** [FluidTYPO3/fluidcontent#212]
Sometimes it happens, that the #Fluid Content Type# is set to the default value ''
Then we get an error in the frontend

Template could not be loaded. I tried "..../typo3conf/ext/fluidcontent/Resources/Private/Templates/Content/Default.html" 

If we could just add a dummy template file for that?

Like this?
File: EXT:fluidcontent/Resources/Private/Templates/Content/Default.html

    <div xmlns="http://www.w3.org/1999/xhtml" lang="en"
         xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
         xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">
    
      <f:layout name="Content" />
    
      <f:section name="Configuration">
        <flux:form id="default" >
        </flux:form>
      </f:section>
    
      <f:section name="Preview">
      </f:section>
    
      <f:section name="Main">
      </f:section>
    
    </div>

**Comment by xf-** [comment]
I think that is not a good idea because a mistake is maybe missed.
Maybe improve the message, why this is happening.

**Comment by cedricziel** [comment]
True. I dont think falling back every little piece is the right way. The value is  obviously an error. @NamelessCoder any thoughts?

**Comment by GuidoJansen** [comment]
The Problem lies here with the backend editors of content. They are not aware, that it is an error if they choose 'Fluid Content Type'. The whole page will break. It would be better to have the page show with that very CE as empty CE rather than break alltogether.

**Comment by cedricziel** [comment]
Let's try to not see it this way.

If this is not about escalation but a default empty template, I'd be in. But IMHO we need a flash message clearly stating this is an error state.

**Comment by GuidoJansen** [comment]
Agree

**Comment by cedricziel** [comment]
Thx for pointing, Guido!

**Comment by GuidoJansen** [comment]
Thx for making this awesome extension

**Comment by NamelessCoder** [comment]
Implemented.
