### ISSUE TITLE
Weird pageTsConfig generated if Resources/Private/Templates/Content doesn't exist

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [FluidTYPO3/fluidcontent#214]
Hi FluidTYPO3 gurus!

I just upgraded to all dev versions of FluidTYPO3 (on TYPO3 6.2 latest master) and switched to the "new" TypoScript registration via ext_tables.php/ext_localconf.php. I now register my provider extension via ``\FluidTYPO3\Flux\Core::registerProviderExtensionKey('myext', 'Content');`` and if at least on content template is found at ``Resources/Private/Templates/Content`` all works as it should.

But: ~~**If no file is found** in~~ If folder ``Resources/Private/Templates/Content`` doesn't exist *all other template files* from  ``Resources/Private/Templates`` and from all subfolders are included in ``pageTsConfig`` as ``mod.wizards.newContentElement.wizardItems.Content.elements.xyz``.

Example: A template from EXT:formhandler is stored under ``Resources/Private/Templates/Plugins/Formhandler/Forms/Contact-Basic/Email/User.html``. Following TS is put in ``pageTsConfig``:

````
			mod.wizards.newContentElement.wizardItems.Content.elements.myext_Plugins_Formhandler_Forms_Contact-Basic_Email_User_html {
				icon = ../typo3conf/ext/fluidcontent/Resources/Public/Icons/Plugin.png
				title = 
				description = LLL:EXT:/Resources/Private/Language/locallang.xlf:flux..description
				tt_content_defValues {
					CType = fluidcontent_content
					tx_fed_fcefile = myext:Plugins/Formhandler/Forms/Contact-Basic/Email/User.html
				}
			}
````

It's clear: If your extensions doesn't provide content elements it shouldn't be registered as a content provider. But what about clueless people like me who simply remove the example element generated by EXT:builder?

**Comment by NamelessCoder** [comment]
Hi @georg-tiefenbrunn,

Yeah that's **definitely** not the intended behavior! I'm not sure why this happens but I suspect it is either because an unexpected path gets passed to the GeneralUtility::getFilesInFolder method or that the `glob` expression that gets generated, is too loose and matches parent folders if folder has no files.

I believe the problem would be in the ContentService of fluidcontent - if you feel like digging for a solution.

**Comment by georg-tiefenbrunn** [comment]
Hi @NamelessCoder, I'm back from 'digging'.

In function ``ConfigurationService->getContentElementFormInstances()`` ``$templateRootPath`` is set to ``$templateRootPath . 'Content/'`` only if the folder ``Resources/Private/Templates/Content`` exists (see https://github.com/FluidTYPO3/fluidcontent/blob/development/Classes/Service/ConfigurationService.php#L230).

I think we can simply omit the extension/template path if folder  'Content/' doesn't extists:
~~~~
-			if (TRUE === file_exists($templateRootPath . 'Content/')) {
-				$templateRootPath = $templateRootPath . 'Content/';
-			}
+			if (TRUE === file_exists($templateRootPath . 'Content/')) {
+				$templateRootPath = $templateRootPath . 'Content/';
+			} else {
+				continue;
+			}
~~~~

**Comment by NamelessCoder** [comment]
Looks like the right place and way to solve that one. Would you mind PR'ing? ;)

**Comment by georg-tiefenbrunn** [comment]
done.
