### ISSUE TITLE
[BUG] Drag&Drop is broken

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/fluidcontent#218]
With the latest development branches (flux,fluidpages,fluidcontent) drag&drop does not work for me.
No frontend bug is visible. After d&d the element goes to its new position.
But the database isn´t updated. So after a reload the element is still on its old place.

I forgot to say, this is with TYPO3 6.2.9.
D&D works with page-columns but fails with FCEs.
I also did a new clean install which showed the same bug.

**Comment by NamelessCoder** [comment]
Should be restored now. The styling may not be optimal at this point but the function should be okay.
