### ISSUE TITLE
Fluid content element with a grid column can be cut&pasted into itself.

### ISSUE THREAD

**Issue by ALRO** [FluidTYPO3/fluidcontent#220]
As the title says, if you cuts a fluid content element, there is the option to paste it into a column of itself.

If you do this, TYPO3 will happily comply and manifacture some deadly recursion. All hell break loose - the page module will no longer be able to display that page, and the element can in no way be deleted without direct DB Access.

It would be great if either it was not possible at all to do this action, or if it was at least possible for a Content Editor to undo this error without having to access the database directly.

**Comment by xf-** [comment]
Confirmed

**Comment by xf-** [comment]
https://github.com/FluidTYPO3/flux/pull/859 should improve it, but grid in grid pasting without direct parent would still create a endless loop.
Like i wrote thats not normal, make proper use of page layouts.

**Comment by xf-** [comment]
We added a small protection, but if you put widget in widget and has no direct parent it is still possible.

**Comment by NamelessCoder** [comment]
Immediate issue is fixed; technically, this issue is fixed according to the description but we are aware of and will be solving the related issue that you can paste a parent into a child that isn't a direct descendant of the parent (e.g. child at level 2+).
