### ISSUE TITLE
Error in CMS 7

### ISSUE THREAD

**Issue by mhmli** [FluidTYPO3/fluidcontent#221]
Core installed via wget in a brand new empty webroot. FluidTYPO3 Distribution package loaded and executed. Switch to Page view:

Fatal error: Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::array_merge_recursive_overrule() in  […]/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php on line 121

**Comment by NamelessCoder** [comment]
The EXT:site distribution will install the TER versions and those are currently not compatible with TYPO3 7(.1). You'll have to wait a bit longer for those TER versions to become compatible. Meanwhile, you can check out the `development` branches of all FluidTYPO3 extensions before you install via EXT:site.
