### ISSUE TITLE
[TASK] Suggestion for UX

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidcontent#222]
Hi there,

I would like to suggest this:

![suggestion](https://cloud.githubusercontent.com/assets/2902073/6651738/f7a01a68-ca52-11e4-9fe3-7fc0e98c2229.png)

I think that it makes sense and is aligned with the approach

**Comment by jmverges** [comment]
![result_ux](https://cloud.githubusercontent.com/assets/2902073/6652180/b6d58f9a-ca66-11e4-9ee8-c2b81f147c5b.png)

**Comment by NamelessCoder** [comment]
Applied in https://github.com/FluidTYPO3/fluidcontent/commit/445f77a9ee642ba7815d34fbe5de99b4851612b5
