### ISSUE TITLE
[BUGFIX] Make Fluidcontent selector compatible with CMS7 Look and feel

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/fluidcontent#223]
tx_fed_fcefile is not maching with bootstrap styles for CMS 7.x

**Comment by jmverges** [comment]
![result](https://cloud.githubusercontent.com/assets/2902073/6652163/036e0540-ca66-11e4-8887-b49861e07f53.png)

**Comment by NamelessCoder** [comment]
Done :)
