### ISSUE TITLE
Select box value of fluid content type changes every time form is saving (TYPO3 6.2.10)

### ISSUE THREAD

**Issue by rabe69** [FluidTYPO3/fluidcontent#226]
$optionValue must be declared before comparing in ContentSelector.php
Fix see: https://github.com/FluidTYPO3/fluidcontent/pull/225

**Comment by Outdoorsman** [comment]
I *think* someone somewhere has fixed this issue because I'm not seeing the problem now with most recent development updates of everything. Anyone else still getting the error after updating?
