### ISSUE TITLE
Eequivalent to TemplaVoila's noEditOnCreation

### ISSUE THREAD

**Issue by hirnschmalz** [FluidTYPO3/fluidcontent#229]
I found an entry in the [IRC Logs](https://fluidtypo3.org/community/irc-logs.html?tx_fluidtypo3org_content%5Bdate%5D=20140319&tx_fluidtypo3org_content%5Bcontroller%5D=Content&cHash=00b3a5c074f810744f0bce3de48bcc31) to this topic  but no further information.

It would be great if fluidcontent would offer an option to create - save - close a new custom content element in one single step. This is especially helpful for wrapper elements like containers for others elements. Now a user has to manually create the element and then click the save and close button.

Markus

**Comment by NamelessCoder** [comment]
Hi Markus,

I would take the opportunity at this point where TYPO3 is being fitted with many new features, to introduce this as a core feature which for example can be defined per CType, in users' options, etc.

This might even make sense for other record types like pages and it certainly makes sense also for non-fluidcontent users ;)
