### ISSUE TITLE
[BUG] v4.2.1 (master) - drag and drop issues

### ISSUE THREAD

**Issue by misterboe** [FluidTYPO3/fluidcontent#230]
when i move a text out of a grid FCE the "relation" is still set. So the element is shown in FE on the new position (outside of the Grid) and in the Grid. 

This only happens with default elements (Text....)

i use CSC

Versions:
"typo3/cms": "7.*",
"fluidtypo3/vhs": "dev-master",
"fluidtypo3/flux": "dev-master",
"fluidtypo3/fluidpages": "dev-master",
"fluidtypo3/fluidcontent": "dev-master"

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/flux/commit/5296b426cce2ce92f7eb7c2d77792425d3c284ad
