### ISSUE TITLE
On Save&New within fluidcontent-container element value of tx_flux_column gets lost

### ISSUE THREAD

**Issue by franzkugelmann** [FluidTYPO3/fluidcontent#231]
It only gets lost under following (quite often happening) circumstances:
1. You created a 2col container element.
2. You click the new button in the first column (and choose header for example)
3. You click "save&new"
4. You get a new content element still with correct value in tx_flux_column, fine.
5. Within that content element you change the CType ie. from header to text. **This change is the crucial part!**
6. You edit your element
7. Again you click save&new
8. Now you have a new text content element, but tx_flux_column is empty -> leading to confused editors.

I could fix that with following setting, so far i see no drawbacks:
$GLOBALS['TCA']['tt_content']['ctrl']['useColumnsForDefaultValues'] .= ',tx_flux_column';
Current default for that is 
$TCA['tt_content']['ctrl']['useColumnsForDefaultValues'] = 'colPos,sys_language_uid';

For me it seems logical to handle tx_flux_column the same as colPos.
Does that make sense to set it with fluidcontent?

$GLOBALS['TCA']['tt_content']['ctrl']['useColumnsForDefaultValues'] .= ',tx_flux_column';

**Comment by DenisMir** [comment]
I can confirm that one as well. As long as I use the _Save&New_ quick action icon I get an empty `tx_flux_children` and `tx_flux_column` for the next content item. This leads to a messed up backend and frontend output.

**Comment by NamelessCoder** [comment]
Sounds like a good way to handle this. We would probably need both `tx_flux_column` *and* `tx_flux_parent` values added here.

**Comment by xf-** [comment]
Fix is merged
