### ISSUE TITLE
Cannot paste elements into empty or on first position of columns of a flux:grid

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/fluidcontent#232]
Using a <flux:grid> for a x-column Element with fluidcontent 4.2.1 and flux 7.2, typo3 cms 6.2.11 it is not possible to paste any content element via the page module into an empty column of this x-column element. Paste icons appear on all columns, but once used, the copied element does not appear in the column where it should have been pasted to. Instead it is created as a new hidden content element outside of any column on the page (colum 18181 set, but probably not inserted correctly into flexform of the column element). 
Pasting does work on columns with at least one existing element in it. But even then it is just possible to pase after an existing element, not on the first position of the column.

Example Code of a multicolumn element as I built it:

```html
{namespace v=FluidTYPO3\Vhs\ViewHelpers}

<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	f:schemaLocation="https://fluidtypo3.org/schemas/fluid-master.xsd"
	xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	flux:schemaLocation="https://fluidtypo3.org/schemas/flux-master.xsd">
	
	<f:layout name="Content" />

	<f:section name="Configuration">
	    <flux:form id="container2Columns" label="Content Container 2 Columns" description="Content Container 2 Columns" options="{Fluidcontent: {sorting: 50}, group: 'FCE'}">
	    	<flux:grid>
				<flux:grid.row>
					<flux:grid.column style="width: 50%;" name="content.col1" label="Content Column 1">
					</flux:grid.column>
					<flux:grid.column style="width: 50%;" name="content.col2" label="Content Column 2">
					</flux:grid.column>
				</flux:grid.row>
			</flux:grid>
			<flux:field.select name="backgroundColor" label="Background Color" items="{white : 'white', grey : 'grey'}" />
	    </flux:form>
	</f:section>
	
	<f:section name="Main">
		<div class="{backgroundColor}-background paddings6">
			<div class="container">
				<div class="row">
			        <div class="grid_6">
			            <flux:content.render area="content.col1" />
			        </div>
			        <div class="grid_6">
			            <flux:content.render area="content.col2" />
			        </div>
				</div>
			</div>
		</div>
	</f:section>
	
</div>
```

**Comment by mkrappitz** [comment]
Or is this to be posted in the flux issues?

**Comment by kaptankorkut** [comment]
+1

**Comment by NamelessCoder** [comment]
Likely cause is use of `.` in name of content column. This works when you place elements relative to existing ones (because the column name is taken internally) and in root columns (because the column name is not used), but does not work in this specific case because the name of the field has to be passed as URL parameter that gets mangled by TYPO3.

Please try without dots in the name. You'll need to relocate existing content afterwards.

**Comment by mkrappitz** [comment]
Thanks a lot for looking into this. I tried this on one of my column elements. But still pasting elements from some page template column into it results in the pasted element only landing in the current column of the page template. Pasting elements from inside another column element results in the pasted element landing the origin column element, not in the target column element.
Besides that, if naming of columns must not contain dots, this should to be added to the documentation.

**Comment by mkrappitz** [comment]
In another project I set up a grid like this, so not dots any more:

```html
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	f:schemaLocation="https://fluidtypo3.org/schemas/fluid-master.xsd"
	xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	flux:schemaLocation="https://fluidtypo3.org/schemas/flux-master.xsd"
	xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	v:schemaLocation="https://fluidtypo3.org/schemas/vhs-master.xsd">
	
	<f:layout name="Content" />

	<f:section name="Configuration">
	    <flux:form id="containertwocolumn" label="Inhaltscontainer 75% 25%" description="2 spaltiger Inhaltscontainer, dessen Inhalte mit 75% Breite links und 25% rechts dargestellt werden." options="{group: 'DECI Elemente'}">
	    	<flux:grid>
				<flux:grid.row>
					<flux:grid.column style="width: 75%;" name="contentLeft" label="Inhalt links">
					</flux:grid.column>
					<flux:grid.column style="width: 25%;" name="contentRight" label="Inhalt rechts">
					</flux:grid.column>
				</flux:grid.row>
			</flux:grid>
	    </flux:form>
	</f:section>
	
	<f:section name="Preview">
		<flux:widget.grid />
	</f:section>
	
	<f:section name="Main">
		<div class="colBox clearfix">
			<div class="colLeft">
				<flux:content.render area="contentLeft" />
			</div>
			<div class="colRight">
				<flux:content.render area="contentRight" />
			</div>
		</div>
	</f:section>

</div>
```

Neither pasting nor drag-dropping content into empty columns does work. 
TYPO3 6.2.12, flux 7.2.0, fluidcontent 4.2.1, vhs 2.3.2, provider extension built by latest EXT:builder. Only other extension in the system are realurl, news, metaseo, pmkshadowbox.

So there is something seriuosly broken.

**Comment by BenjaminBeck** [comment]
I also noticed that copy&paste to the first position of a fluid content area does not work.
But i have no problems with d&d.
(latest dev releases)

**Comment by BenjaminBeck** [comment]
@NamelessCoder I think this issue can be closed (fixed by FluidTYPO3/flux@bab7ca6 )

**Comment by mkrappitz** [comment]
I just changed these 2 lines in my flux extension, but this does neither fix the pasting nor the drag and drop. So please reopen.
This patch is as the function name "drawPasteIcon" states also about the drawing of the paste icon, I would have wondered how this should have fixed the correct saving of elements placed into column containers.

**Comment by hkarvasonis** [comment]
Do you use the "fluidcontent_core" extension in your installation?

I have exactly the same issue like you and i am not using "fluidcontent_core".
After i installed it, this issue was fixed.

I don't need that extension though and i just found out that the following line in the ext_localconf.php and ext_tables.php is actually the one that is fixing this issue:
\FluidTYPO3\Flux\Core::registerConfigurationProvider('FluidTYPO3\FluidcontentCore\Provider\CoreContentProvider');

I am not sure what the relation is between flux and fluidcontent_core is, but this wasn't happening in the past without using the fluidcontent_core extension.

**Comment by mkrappitz** [comment]
I'm not using EXT:fluidcontent_core and I don't want / need it. 
Thanks for this info, will try this for a temporary solution, but anyway this should be properly fixed without having to install fluidcontent_core.

**Comment by hkarvasonis** [comment]
I agree with you, but i am not familiar about all the details and why that extension should be needed for that to work.
I have posted a similar comment at https://github.com/FluidTYPO3/flux/issues/573 where there is a bigger discussion about copying/pasting issues.

**Comment by mkrappitz** [comment]
Tried it. It fixes the drag and drop, but not the pasting. Still this is not a real solution.

**Comment by hkarvasonis** [comment]
I am not sure if we are doing the same thing, but It fixes pasting and pasting as reference for me when i paste a content element inside a fluidcontent content element.
