### ISSUE TITLE
Dragging CE's into Grid ist broken

### ISSUE THREAD

**Issue by heiko-hardt** [FluidTYPO3/fluidcontent#233]
Hi, since the update Flux 7.2, i'm not able to drag regular content-elements into a fluid-content grid.
It seems that there are problems updating the "tx_flux_column" field.
If you want to reproduce: Create a text-ce outside and drg this into a fluid-content grid

Im using TYPO3 6.2.11 and current versions of flux, fluidcontent and fluidpages

Kind regards

**Comment by misterboe** [comment]
same here

**Comment by misterboe** [comment]
there are also problems when i use FCC

**Comment by CarstenD** [comment]
same here

**Comment by coding46** [comment]
@CarstenD
"Same here" for what? For the fix or the issue? :)

**Comment by CarstenD** [comment]
both :-) .... first i got the same bug, but the patch fixed my it.
