### ISSUE TITLE
Can't copy CE's from other languages

### ISSUE THREAD

**Issue by Hupps** [FluidTYPO3/fluidcontent#234]
I've experienced some trouble with copying CE's from other languages 

e.g. I have a german impress-page and the same page as english translation, now I want to copy the translated CE's into an other page. 

Now I can't Drag & Drop the elements which is similar to this one:
https://github.com/FluidTYPO3/fluidcontent/issues/233
I tried the bugfix, but it didn't work. 

Second problem is, that in the contextmenue there is no entry for copying the CE (in the translated data) only in the "original" language I can copy or cut the CE. 

Thank you & kind regards

**Comment by NamelessCoder** [comment]
The first issue we will of course take care of - in the other issue ;)

The not being able to copy-to-clipboard those records that are already translations is, as far as I am aware, both completely by design and controlled by TYPO3 itself - with no way to change that in the core.
