### ISSUE TITLE
Tab in Content element Wizard disappear 

### ISSUE THREAD

**Issue by mischka** [FluidTYPO3/fluidcontent#242]
I have a strange issue. After clearing the System-Cache via InstallTool the Wizard locks ok with the FCE etc. But sometimes this tab disappear and the cf_fluidcontent table entry witch store the TS-Config for the FCE contains only (correct serialized)

    [PIDinRootline = 2]
    [GLOBAL]

is there a problem with the regeneration of the cache? Maybe it happened when the cache expires?

**Comment by lsascha** [comment]
Same issue here. I am still using fluidcontent v4.1.1 with flux v7.1.2 though in fear there are more issues after update. (had bad experiences after some updates previously). So is that bug still there?

**Comment by xf-** [comment]
Hi,
i had no problems with 7.3 and master.
7.1 is outdated.

Can you test it against 7.3.1 or with current development flux and fluidcontent. I also use fluidcontent_core.

**Comment by xf-** [comment]
Can confirm it.
After clearing the cache in installtool and (directly) accessing the wizard the tabs are missing.
Could be the hook is to late.

@jmverges could you investigate this?

**Comment by jmverges** [comment]
Are we talking about the tabs generated with by fluidcontent and not the other ones, right? I can reproduce this behaviour.

**Comment by NamelessCoder** [comment]
Implemented in 931592f2b01bd8ba298a37ccfbfd386207c4b175
