### ISSUE TITLE
Add context sensitive help (CSH) to FlexForm fields

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [FluidTYPO3/fluidcontent#245]
I tried adding csh to fields generated by fluidcontent (TYPO3 7.4-dev/dev-master and FluidTYPO3/dev-development installed by composer) and noticed that all fields use data-table ``tt_content.pi_flexform..fluidcontent_content`` (note the double .. between ``pi_flexform`` and ``fluidcontent_content``).

After adding ``	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addLLrefForTCAdescr('tt_content.pi_flexform..fluidcontent_content', 'EXT:myProviderExt/Resources/Private/Language/locallang_csh.xlf');
`` to ``ext_tables.php`` and providing ``<trans-unit id="filedID.description">`` (without ``flux.formID.type``) csh is displayed in BE.

Is there an easier way like ``flux.formID.type.name-of-the-element`` for form labels also for csh? The [manual](https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/language-usage.html) does not mention csh.

Those double ``..`` in ``tt_content.pi_flexform..fluidcontent_content`` look odd.

**Comment by jmverges** [comment]
Hi @georg-tiefenbrunn,

I can reproduce it, let us check what is going on.

**Comment by jmverges** [comment]
Hi @georg-tiefenbrunn,

after a investigation we found it is a core issue and we are reporting it. You can take a look here: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/backend/Classes/Form/Container/FlexFormTabsContainer.php#L81 where is not checking if list_type is empty. Take a look to the a todo around.

I like your suggestion however there is no way to implement it at the moment. Once core issue it fixes you will need to include \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addLLrefForTCAdescr('tt_content.pi_flexform.fluidcontent_content', 'EXT:myProviderExt/Resources/Private/Language/locallang_csh.xlf'); in your provider extension. We will include it in builder and documentation.

Thank you for reporting!

**Comment by NamelessCoder** [comment]
A bit more detail from our internal IRC log:

```
[17:22:15]  <@NamelessCoder>	no, this won't work... sorry jmverges
[17:22:58]  <jmverges>	NamelessCoder what won't work?
[17:23:04]  <@NamelessCoder>	the csh thing
[17:23:15]  <@NamelessCoder>	that whole feature is designed to work with a fixed flexform DS
[17:23:36]  <@NamelessCoder>	ours is dynamic, based on another field, read from a template or PHP
[17:23:54]  <@NamelessCoder>	so every Flux field in a fluidcontent regardless of type would share the same locallang file
[17:24:35]  <jmverges>	so... what is the solution then?
[17:24:43]  <@NamelessCoder>	name a field "settings.name" in element A and B, and both will have the same CSH. Trying to replace it will override both; there's no way to split it into a file per fluid content type
[17:25:11]  <@NamelessCoder>	there is no solution. Our identifier for a template cannot be used in an XLF reference
[17:25:36]  <jmverges>	shit, we are sell then we cannot introduce csh, right?
[17:26:12]  <@NamelessCoder>	we simply cannot. Doing so would imply turning every fluidcontent type into a dedicated CType and... well... that's a disastrously breaking change at this point.
[17:27:52]  <jmverges>	so then is not a core issue
[17:28:21]  <@NamelessCoder>	the only way we could be doing this right, is if each TCA element allowed an additional "csh" attribute like the "label" attribute, so that we could generate a reference just like we do for the label.
[17:29:22]  <@NamelessCoder>	if that could be added as a core feature for TCA we can use that from day one ;)
```

If anyone decides to run with creating this tiny but powerful addition to TCA/CSH for the TYPO3 core, feel free to add me as reviewer and I'll give my +1.

**Comment by jmverges** [comment]
Well, anyway https://review.typo3.org/#/c/41988/ the issue is there ;)

**Comment by georg-tiefenbrunn** [comment]
Thanks for the fixes and the detailed information!

@jmverges: I can confirm your approach is working on TYPO3 7 (composer). I wasn't aware of the collision between multiple elements, but adding ``,tx_fed_fcefile`` to ``$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds_pointerField']`` solves this. At a quick glance I didn't experience strange behavior of the CMS after extending ds_pointerField (Core CSH works fine).

**Comment by NamelessCoder** [comment]
@georg-tiefenbrunn can you confirm whether using `tx_fed_fcefile` as DS pointer field causes bad LLL reference formatting, e.g. reference contains a colon?

**Comment by georg-tiefenbrunn** [comment]
**Short version:** ``fieldName.description`` values in *locallang_csh_xyz.xlf* files work as expected in TYPO3 7.4-dev (via composer), ``fieldName.details`` values *do not* work because of sanitizing of url param ``tfID`` in EXT:cshmanual (which doesn't allow ``:``).

**A bit more details:**
Sorry, @NamelessCoder, I'm not sure what you mean with 'reference formatting'.

I created a fresh fluid CE (TYPO3 and fluidTYPO3 via composer) to be sure no cached values are involved. Using ``<flux:field.input name="testFieldA" />`` in template file *Test.html* and adding ``\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addLLrefForTCAdescr('tt_content.pi_flexform.fluidcontent_content.my_provider:Test.html', 'EXT:my_provider/Resources/Private/Language/locallang_csh_Test.xlf');`` to *ext_tables.php* correctly displays the ``testFieldA.description`` value defined in *locallang_csh_Test.xlf*. No colon, just as it should be.

File *locallang_csh_Test.xlf*:
```xml
<trans-unit id="testFieldA.description">
	<source>test field A description</source>
</trans-unit>
```
Rendered tooltip:
```html
<div class="popover-content"><p class="t3-help-short">test field A description</p></div>
```
Providing ``testFieldA.details`` value in *locallang_csh_Test.xlf* leads to a clickable tooltip (which is indicated by an added ``»`` after ``testFieldA.description`` value). The tooltip label ist still as it should be (again no colon):

Rendered tooltip:
```html
<div class="popover-content"><p class="t3-help-short tipIsLinked">test field A description<span class="t3-icon fa t3-icon fa fa-angle-double-right"> </span></p></div>
```

**But:** Opening the TYPO3 Inline User Manual (Inline Help) by clicking on the tooltip fails to display the desired ``testFieldA.details`` value. Instead of the details the main page/ToC of the inline help is displayed. The ToC lists my added help entry as ``tt_content.pi_flexform.fluidcontent_content.my_provider:Test.html`` in section 'Other', but following this link has no effect.

I first blamed the non escaped characters in the generated url (like the ``:`` between ``fluidcontent_content.my_provider:<tx_fed_fcefile>``; examle url ``http://<host>/typo3/index.php?M=help_cshmanual&moduleToken=<token>&tfID=tt_content.pi_flexform.fluidcontent_content.my_provider:Test.html.testFieldA``) but it's the sanitizing of ``tfID`` in [line 107](https://git.typo3.org/Packages/TYPO3.CMS.git/blob/HEAD:/typo3/sysext/cshmanual/Classes/Controller/HelpModuleController.php#l107) of *typo3/sysext/cshmanual/Classes/Controller/HelpModuleController.php* which doesn't like the ``:``(

**Comment by NamelessCoder** [comment]
Yeah, that's what I feared. The colon is causing problems - it simply isn't valid as part of the LLL reference :/ I'm afraid there's nothing we can do about this currently but the suggested TCA change I mentioned would make this possible!

**Comment by georg-tiefenbrunn** [comment]
@jmverges: I found a nasty implication in the CMS of adding ``,tx_fed_fcefile`` to ``$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds_pointerField']``. This leads to three values (``list_type,CType,tx_fed_fcefile``) set for *ds_pointerField*. **WARNING:** This will break the rendering of flexforms from field `tt_content.pi_flexform` (e.g. CType *login* or *table*). Instead of the value defined in ``$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds']['*,<CType>]`` the default flexform from ``$GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds']['default]`` is used.

See https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Flex/Index.html#columns-flex-properties-ds-pointerfield

> Up to two field names can be specified comma separated.
