### ISSUE TITLE
fluidcontent not working in typo3 7 due to '/' in ConfigurationService.php

### ISSUE THREAD

**Issue by vinayn** [FluidTYPO3/fluidcontent#246]
In ConfigurationService.php line no 245 has extra  '/'. Due to this fluidcontent is not working in Typo3 7.
The code is as below
```php
$files = GeneralUtility::getAllFilesAndFoldersInPath($files, $templateRootPath . '/' . $controllerName, 'html');
```
Once the code is changed to 
```php
$files = GeneralUtility::getAllFilesAndFoldersInPath($files, $templateRootPath. $controllerName, 'html');
```
fluidcontent is working as expected

**Comment by xf-** [comment]
Double works fine on my system. We added a / after controllerName for recursion in 7.x
Can you give us more informations or test it with development branch?

**Comment by xf-** [comment]
We tested the issue and it works.
If this is still an issue, please send us more informations about the system.

**Comment by vinayn** [comment]
Due to double "/' fluid content is not working in my windows 7 machine.I am using php 5.6.x version

**Comment by xf-** [comment]
Windows issue
similar to https://github.com/FluidTYPO3/flux/issues/814
In general, we think T3core should handle paths.

(We have no windows system to confirm this issue or fix it, if it is outside of T3core. Anybody is welcome to send a Pull Request)

**Comment by NamelessCoder** [comment]
A fix is coming as part of the TYPO3 core itself. Windows file path compatibility is currently not available in Fluid itself and should/will be implemented there instead.
