### ISSUE TITLE
Content elements should be overwriteable by another extension

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/fluidcontent#247]
This is maybe a false positive, but I cannot get it work, so please don't judge me.

It seems that content elements cannot be overwritten by another extension, even the layout & template-paths are overwritten by Typoscript.

For example:
abc:Panel.html has defined a global logic as a content element.
xyz:Panel.html is the same and should use the logic from abc, but uses another layout/design and also sets an additional parameter for abc:viewhelper.

But the xyz:Panel.html is ignoried and only abc:Panel is executed.
Is there any way to achieve this?

Edit:
It works fine with fluidcontent: 4.1.1 (flux: 7.1.2, fluidpages: 3.1.2) -> xyz:Panel is shown
fails after updating to fluidcontent: 4.2.2 (flux: 7.2.1, fluidpages: 3.2.3) -> abc:Panel is shown

Edit:
"'templateRootPath' (singular) and 'overlays' are deprecated" - do you also removed support for plugin.tx_foo.view.templateRootPath? serioulsy?

Only works with templateRootPaths now on TYPO3 6.2.12, but not on 6.2.13 ???

**Comment by xf-** [comment]
If you take a look in database it stores the extension and filename:
e.g. myprovider:Example.html

Because of the unique identifier id it could be possible to override something. 

Overriding will split the same element in old and new version. This is a bad idea in my eyes. Create a project specific provider.
FCC allows variants and versions.

@NamelessCoder close or?

**Comment by webloft** [comment]
I don't want to override the Provider-ID in the database. Only the TEMPLATE-Path which is used to render.

This works in previous versions. In the current release, templateRootPath is completely ignored , because support is removed, right? 

Sometimes (after whole cache reset) templateRootPaths.10 for Example will be accepted, but sometimes NOT and the path is NOT overwritten. The configuration wasn't touched. There is also NO other path which take precedence - only a base path in provider A which sould be overwritten through provider B.

I want to know if this behaviour is right - I think not, its not consistent, so it is a bug. Please investigate.

**Comment by NamelessCoder** [comment]
You can achieve this by adding additional `templateRootPaths` (note the plural) with a higher index than the default templates. Be aware that depending on your version of Flux, this default index is either `10` or `0` so I advise you choose a value above `10`.
