### ISSUE TITLE
Missing icons in newContentElement.wizard because of absolute paths

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [FluidTYPO3/fluidcontent#253]
Since [TYPO3.CMS 195fbb3fe088215d8c3128a208c35b6fad6db157](https://git.typo3.org/Packages/TYPO3.CMS.git/commit/195fbb3fe088215d8c3128a208c35b6fad6db157) (TYPO3 7/master) icons are missing in newContentElement.wizard for fluidcontent elements. TYPO3 core doesn't support the absolute icon paths (``/typo3conf/ext/myext/...``) used by EXT:fluidcontent anymore. I've created a bug report [on forge](https://forge.typo3.org/issues/68575) about this.

**Comment by xf-** [comment]
Yeah the path handling is ... 
I have a patch with a unfinished feature (needs to use core features).
https://gist.github.com/xf-/91d4dec1a21e51e613de

**Comment by georg-tiefenbrunn** [comment]
https://forge.typo3.org/issues/68575 was Accepted and set to Target version 7.4 which should be finished  in early august.

**Comment by xf-** [comment]
yeah, but resize the icon is also a nice thing ;)
