### ISSUE TITLE
fluidcontent tries to render preview for non-fluidcontent elements

### ISSUE THREAD

**Issue by georg-tiefenbrunn** [FluidTYPO3/fluidcontent#260]
I recently added a preview hook to my TYPO3 CMS/flux/fluidcontent (composer master/dev/dev) installation. For all non-fluidcontent elements the message *'Fluid Content type not selected - edit this element in the TYPO3 backend to fix this!'* is added to the content preview in page module.

Function `FluidTYPO3\Flux\Provider\AbstractProvider->getPreview()` is called for all CTypes. I expected fluidcontent to only render its preview for `CType=fluidcontent_content`. Am I wrong with this assumption?

Adding a `FluidTYPO3\Fluidcontent\Provider\ContentProvider->getPreview()` function which checks if `CType == fluidcontent_content` seems to solve this.

```php
	/**
	 * Returns array($header, $content) preview chunks
	 * 
	 * @param array $row The record data to be analysed for variables to use in a rendered preview
	 * @return array
	 */
	public function getPreview(array $row) {
		$previewContent = '';
		if (TRUE === isset($row['CType']) && $this->contentObjectType === $row['CType']) {
			$previewContent = $this->getPreviewView()->getPreview($this, $row);
		}
		return array(NULL, $previewContent, empty($previewContent));
	}
```

All those flux/fluidcontent provider stuff is definitely some levels above my coding skills. But let me know if my solution is the right way to solve this and if I should open a PR for this.

**Comment by smichaelsen** [comment]
This is also bugging me.
I also feel like there has to be this check you proposed.

**Comment by NamelessCoder** [comment]
This one should now be solved in our development branches. You will need both Flux and Fluidcontent pulled. I will leave this issue open just in case the committed patches actually made something else fail, which is possible.

See also https://github.com/FluidTYPO3/fluidcontent/commit/c05dbd237dedbf84c69583626ef7096caf9dcb99

**Comment by NamelessCoder** [comment]
Closing, will reopen if there are reports of this same issue popping up again (which it definitely shouldn't, since the preview is now removed).
