### ISSUE TITLE
Strange problem with ext_localconf hook

### ISSUE THREAD

**Issue by morinfa** [FluidTYPO3/fluidcontent#265]
With v4.3.1, a hook has been added in ext_localconf.php file :
<pre>$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['GLOBAL']['extTablesInclusion-PostProcessing']['fluidcontent'] = 'FluidTYPO3\Fluidcontent\Backend\TableConfigurationPostProcessor';</pre>
This hook breaks a custom config where I override the default BackendInterface :
<pre>config.tx_extbase {
	objects {
		TYPO3\CMS\Extbase\Persistence\Generic\Storage\BackendInterface.className = MyExt\ProxyBackend\Persistence\Storage\ProxyBackend
	}
}</pre>
My proxybackend is no more called because of this hook. If I comment it in fluidcontent localconf file, my proxy is correctly called.
I don't really understand how this hook has an impact on this standard override ?

**Comment by NamelessCoder** [comment]
Hi Fabrice,

That's quite strange but I *think* it might have something to do with one or more instances of Singletons having been registered and then reused, but that those instances were created at a point *before* your code. This would all depend on the extension load order (and it is a big guess, I admit).

In any case: the issue should be gone if you give the `development` branch a try. We've added a condition that makes sure the hook you have problems with here, only gets called in the backend.

If however you were trying to add a custom database backend to use in the TYPO3 backend (which would be the rare use case, but it happens!) then the only way you can work around this is to *make sure your extension gets loaded before fluidcontent*.

And finally: if none of this helps at all and you debug further, and you discover which Singletons cause this, don't hesitate to request we reopen this issue. Maybe we can find a way to unregister or reset the Singleton (if/when we know which one it might be).

Cheers,
Claus

**Comment by morinfa** [comment]
Hi Claus,

The load order doesn't seem to have any impact.
But it works with the condition, thanks.

Regards,
Fabrice
