### ISSUE TITLE
Content Item Icons don't show up since version 4.3.0

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/fluidcontent#266]
After the update to `fluidcontent` version 4.3.0 I don't see the content item icon in the content item selection screen. I'm using the latest 6.2 LTS patch version and all of the latest FluidTypo3 extensions. 

![bildschirmfoto 2015-08-12 um 10 15 18](https://cloud.githubusercontent.com/assets/157281/9219423/17f68334-40db-11e5-937a-0dd736d80150.png)

**Comment by xf-** [comment]
needs flux dev until the release

**Comment by DenisMir** [comment]
It would be great if such implications would be mentioned in the changelog.
