### ISSUE TITLE
PHP Error - "Unable to fork ['/usr/bin/gm' 'identify' '/var/www/web/typo3conf/ext/fluidcontent/Resources/Public/Icons/Plugin.svg'[0]” 

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/fluidcontent#267]
Using TYPO3 7.4 and all development versions of flux, fluidpages and fluidcontent i am receiving a strange error in the backend, see attached file.

any ideas?
<img width="1352" alt="bug_fluidcontent" src="https://cloud.githubusercontent.com/assets/3888860/9224668/8f4f421c-4104-11e5-9e7a-62068c2a8592.png">

**Comment by cedricziel** [comment]
This is a general error about graphicsmagick dying on svg conversion.

Your next steps could be:

* check if you can convert manually (`convert source.svg target.svg` / `/usr/bin/gm identify file.svg`)
* if it cannot identify the format, you may have exported it in an unconventional way, try it with a simpler image, probabaly one vector would be enough, maybe just the mime type is unknown
* install the library that graphicsmagick can utilize to process svgs
* if that doesnt help: please update graphicksmagick

I do not consider this to be a general problem with any of the FluidTYPO3 extensions. - Feel free to reopen if you cannot reproduce this with a standard TYPO3 7.4 *without* FT3 extensions.

Cheers,
Cedric

**Comment by xf-** [comment]
We use imageUtility - your setup has a incorrect configuration.

**Comment by smichaelsen** [comment]
I ran into the same problem and feel like it should be changed in fluidcontent. Dropping the `Plugin.svg` and replace it with a png wouldn't be much of a problem and you wouldn't require people to install/configure additional server side tools (remember: not everybody has the rights and/or the abilities to do this).
