### ISSUE TITLE
What is that? Invalid table:field "tt_content:content_options". I do not use fluidcontent_core

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/fluidcontent#271]
Hello, everybody!

I do not use fluidcontent_core but get this error
~~~
Invalid table:field "tt_content:content_options" - does not exist in TYPO3 TCA.
~~~

Why?

TYPO3 version 6.2.14

At "Manage Extensions" i have:
VHS
FLUX
FLUIDPAGE
FLUIDCONTENT
All from TER

**Comment by NamelessCoder** [comment]
You could do a `grep -r content_options typo3conf/ext/` to find out where the reference is.

**Comment by NamelessCoder** [comment]
Hey @typo3ua - any updates about this? Did you find the place that references this field - did you solve it already?

**Comment by typo3ua** [comment]
I sorry ... I found problem (error) in my code.

Thanks.

**Comment by NamelessCoder** [comment]
Thanks @typo3ua
