### ISSUE TITLE
Fluidcontent causes strange internal server-error?

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/fluidcontent#276]
We have some strange internal server-errors with FluidContent FCE Elements (f.e. 2-column-divider from EXT:fluidbootstraptheme).

Any idea what is wrong there?

**Comment by xf-** [comment]
Please add more informations.
For example PHP error log.

**Comment by typoworx-de** [comment]
I was able to find the final culprit after investing some time of research. FluidContent is fine. Some strange "loop" in RTE / parseFunc inside the Col-Element was causing the strange misbehaviour.
