### ISSUE TITLE
do not allow fluidcontent as child of itself

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/fluidcontent#279]
In the current fluidcontent (4.3.2) it is possible to assign the the fluidcontent-element to itself as child. This leads to a inifinit loop and you cant move or delete this element. Page view is also not accessible. I have to delete the element in database.
You can assign the elment to itself through wierd drag-and-drop actions (in screenshot you can see: if I drag in the right bottom corner I can insert it to itself).
![image](https://cloud.githubusercontent.com/assets/6038909/9871123/b0d1b51c-5b91-11e5-92cb-54812a5d0a43.png)

**Comment by NamelessCoder** [comment]
Fixed in development branch of Flux, will be in next TER release. Fix is implemented by ignoring the move action if moving an element into itself.
