### ISSUE TITLE
Broken Images in WizardTab

### ISSUE THREAD

**Issue by infastra** [FluidTYPO3/fluidcontent#281]
I’m using Typo3 6.2.15, flux 7.2.2, fluidcontent 4.3.2. When I create a new content element, I’ll get broken images in the WizardTab. I could solve this problem by deleting lines 344 to 346 in the class FluidTypo3\Fluidcontent\Service\ConfigurationService (if (0 === strpos($icon, '../')) …). 

Could it be possible that the code was created for Typo3 Version 7.x?

**Comment by NamelessCoder** [comment]
Please give an example of an image URL that's broken, what you expect it to be instead and how you configured the icon path.

**Comment by infastra** [comment]
In the content-template I define the icon path with '../typo3conf/ext/extensionName/Resources/Public/Icons/icon-extension.png'(<flux:form id="elementId"
               options="{group: 'GroupName', icon: '../typo3conf/ext/extensionName/Resources/Public/Icons/icon-extension.png'}">). In the WizardTab I see the icon-Path '../..//typo3conf/ext/extensionName/Resources/Public/Icons/icon-extension.png'. After patching (deleting the lines above) the browser could find the icon with the path '../../../../typo3conf/ext/extensionName/Resources/Public/Icons/icon-extension.png'.

**Comment by NamelessCoder** [comment]
You'll need to assign the icon either by filename convention (template filename `Content/Element.html` means we look for an icon in `Resources/Public/Icons/Content/Element.(png|gif|svg)`) or using `{f:uri.resource(path: '...')}` as value of the "icon" option. We wrapped the link generating in a utility that can create valid icon paths regardless of core version - if you hardcode the path it will only work for one version.

You should be able to make your current code example work like before if you remove the `../` part. But, to get proper support on all versions, you should use either of the suggested methods with convention based icon filename being preferred.

**Comment by infastra** [comment]
I tried your suggestion by using UriResourceViewHelper, but it doesn't work. Here is my code: icon: '{f:uri.resource(path: \'Icons/icon-extension.png\')}'}.
