### ISSUE TITLE
Question regarding exclude fields

### ISSUE THREAD

**Issue by Atomschinken** [FluidTYPO3/fluidcontent#283]
Hi,

i'm looking for a way to show specific fields in content elements only to special be groups/users.
I tried to use the "exclude" attribute in the flux viewhelpers, but it only hides the field from all non admin users completely.

Any help would be much appreciated.

Thank you

**Comment by jmverges** [comment]
Hi @Atomschinken,

I never tried so I don't know if is posible to use: https://fluidtypo3.org/viewhelpers/fluid/master/Security/IfHasRoleViewHelper.html Could you try and give us some feedback?

**Comment by Atomschinken** [comment]
Hi @jmverges,

thank you for that hint. It seems to work quite well with one drawback:
It affects admins too, so i have to put every admin in that group too.

```
<f:be.security.ifHasRole role="1">
    <flux:field.input name="xyz" />
</f:be.security.ifHasRole>
```

The perfect solution would be to add the excluded field to the access right section of users/groups, but i don't know if this is possible at all.

Nevertheless it's a suitable workaround for me, so thank you again.

**Comment by jmverges** [comment]
You are welcome @Atomschinken. 
I think "the perfect solution" is not possible because fields are generated dynamically. 
@NamelessCoder do you have something to add here?
