### ISSUE TITLE
fluidcontent as custom TCA-types

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/fluidcontent#287]
Is there a way to use fluidcontent-elements as TCA-types? If not it would be a nice feature.

**Comment by jmverges** [comment]
Hi @webloft,

I don't understand exactly what are you talking about, could it be related with https://github.com/FluidTYPO3/fluidcontent_core/ approach?

Regards

**Comment by NamelessCoder** [comment]
In theory yes, this would be possible (although it would be a bit messy if all content was added that way). We would need to adapt the ContentProvider to allow triggering on additional CType values and we'd need some way of making a template register itself differently (e.g. create additional `configurePlugin` etc. calls).

But I think it's more than we can make time for before the LTS release. Let's keep this open and consider if for the next minor/major version!

**Comment by webloft** [comment]
@jmverges I'm currently using a Fluid-StandaloneView to render a custom TCA-field in Backend to enhance an input fields usability in pages and tt_content. While at present you can set up custom layout for rendering in Main & Preview, I need this functionality also in Backend-Edit-Mode.

I also want to use this type in pages, tt_content or other tables.
It's more a feature for developers, I think.

So there are 2 main issues:

1) It would be nice if there would be a new section to optionally render the flexform-data in backend  by yourself while editing.

2) The first approach would only affect Fluid-Content elements in tt_content, but you may want to use this technique for other tables too.

The goal:
You create new types with custom backend-layout rendering by creating special Fluid-Content elements and be able to use these new types everywhere, also in other Flux-Forms.

**Comment by NamelessCoder** [comment]
@webloft To clarify, do you mean TCA types as in *the different record field compositions that you can control by setting a "type" field in the record itself* or do you mean *the ability to use a fluidcontent element as if it were any other CType; like custom plugins created as new CType values*?

**Comment by webloft** [comment]
@NamelessCoder The first one, I guess. I want to use the type on any tables, for any possible purpose - also creating/extending palettes.

**Comment by NamelessCoder** [comment]
Right - thanks for clarifying :)

That's a very, very big request and I don't think it will arrive any time soon, but it is on our horizon (and Flux already partially supports using Form etc. instances as TCA for arbitrary record types, including some tricks about reflecting domain models).

https://vimeo.com/74294449 says a little bit about the current supports.

Now, I'll close this but that doesn't mean the feature won't ever be made ;) all it means is that your request will definitely be filled at some point and doesn't need a reminder - but there are some things going on in the TYPO3 core which affect this (positively) giving us exactly the APIs we will require for delivering this feature. In other words: this will happen, but maybe not this or next year!
