### ISSUE TITLE
FLuid content element - referenced shortcut won't update in BE

### ISSUE THREAD

**Issue by chuenniger** [FluidTYPO3/fluidcontent#289]
Hi

I've found an issue. 

If you create a shortcut of a Fluid content element and edit the original element, the referenced element in the backend will not be updated (see screen for details). The FE works fine but not the BE.

Some specs
* TYPO3 CMS 6.2.15
* fluid 6.2.0
* flux 7.2.3
* fluidpages 3.3.1
* fluidcontent 4.3.2

![screen shot 2015-10-13 at 12 02 00](https://cloud.githubusercontent.com/assets/188438/10451767/831b5ff2-71a2-11e5-88b4-ab2931d8de1d.png)

**Comment by hhoechtl** [comment]
It's completely broken in TYPO3 7 and latest master

![Screenshot](https://dl.dropboxusercontent.com/u/39201423/TYPO3-7-fluidcontent-preview-reference.png)

**Comment by NamelessCoder** [comment]
Fixed by #311 thanks to @hhoechtl. Thanks for reporting and including screenshots!
