### ISSUE TITLE
getPageTsConfig is a performance problem with many root templates

### ISSUE THREAD

**Issue by joneppie** [FluidTYPO3/fluidcontent#292]
```getPageTsConfig()``` in ```Classes/Service/ConfigurationService.php```  call ```renderPageTypoScriptForPageUid($pageUid);``` for every root Template in TYPO3-Installation. If you have a Installation with over 2000 domain with there own root template you get over 2000 db-requests only for TypoScript which is in <10 templates.

**Comment by cedricziel** [comment]
Hi Johannes;

I got your mail. The team has an in-person meeting in the coming weeks. And if your issue is not solved up until then, we'll discuss it there. I know the extraordinary situation you're in so please be assured I'll take it to the meetup.

I'm sorry that I can't help immediately.

Cheers,
Cedric

**Comment by joneppie** [comment]
There is another problem with ```getPageTsConfig``` and ```renderPageTypoScriptForPageUid```: It call ```FluidTYPO3\Flux\Service\FluxService::getAllTypoScript()``` which cache TypoScript with the uid from the first call of ```renderPageTypoScriptForPageUid```.

A bad workaround to fix this is include two lines:
```php
	public function getPageTsConfig() {
		$this->backupPageUidForConfigurationManager();
		$this->getContentConfiguration(); //normal call in renderPageTypoScriptForPageUid()
		$pageTsConfig = '';
		...
```

**Comment by higidi** [comment]
@joneppie i can confirm, same problem here

so it's the FuidTYPO3\Flux\Service\FluxServicegetAllTypoScript() is cached and it's impossible to load other template path via typoscript for other root templates

**Comment by joneppie** [comment]
Thats my local Change now:
https://github.com/FluidTYPO3/fluidcontent/compare/development...joneppie:bugfix/%23292

I don't know why all root-Templates must be parsed. I don't find any error without it. That is the reason for not create a pull request.

**Comment by mneuhaus** [comment]
@joneppie i created a pull-request that changes the behavior to only include the current page + rootline 
to get the typoscript templates, could you test, if this helps in your usecase?
