### ISSUE TITLE
displayCond for field "tx_fed_fcefile"

### ISSUE THREAD

**Issue by SventB** [FluidTYPO3/fluidcontent#294]
Can you please add a condition to the field "tx_fed_fcefile"? It is shown in every content element, but makes only sense in content element "Fluid Content".

This is very easy to accomplish:

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('tt_content', array(
	'tx_fed_fcefile' => array(
		'exclude' => 1,
		'displayCond' => 'FIELD:CType:=:fluidcontent_content',
```

**Comment by jmverges** [comment]
Hi @SventB,

this is already added in development version: https://github.com/FluidTYPO3/fluidcontent/blob/development/Configuration/TCA/Overrides/tt_content.php#L16

I'm going to close this issue ;)
