### ISSUE TITLE
Broken images in wizard tab with TYPO3 7.5

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#296]
I'm getting no images for content elements in the "new content element wizard". This happens with TYPO3 7.5, fluidcontent 4.3.3.

`fluidcontent` generates the TypoScript containing the icon setting with a path like
> `typo3/../../typo3temp/pics/430da8f56d.png`

But then `TYPO3\CMS\Core\Imaging\IconProvider\BitmapIconProvider.php` sees that it's not an absolute path and tries to resolve the absolute path with `GeneralUtility::getFileAbsFileName`, which returns an empty string.

Related to #281, #290 and #295.

**Comment by jmverges** [comment]
closed via: #297
