### ISSUE TITLE
Section with no elements: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#298]
I've got a flux form with a `<flux:form.section>` inside, with a single field. The preview section renders the section elements.

When I add a single section element, save it, then remove it and save, the backend preview will show a PHP warning that covers the whole page, making it impossible to do anything:

>  PHP Warning: Invalid argument supplied for foreach() in typo3/sysext/fluid/Classes/ViewHelpers/ForViewHelper.php line 114

This is with TYPO3 7.5, fluidcontent 4.3.3, flux 7.2.4.

Minimal example content element:
```
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers">
  <f:layout name="Content" />

  <f:section name="Configuration">
    <flux:form id="test" options="{group: 'FCE'}">
      <flux:form.section name="settings.links" label="Links">
        <flux:form.object name="link" label="Link">
          <flux:field.input name="url" label="URL" required="1"/>
        </flux:form.object>
      </flux:form.section>
    </flux:form>
  </f:section>

  <f:section name="Preview">
    <f:for each="{settings.links}" as="link">
      {link.link.url}<br/>
    </f:for>
  </f:section>
</html>
```

The flexform XML stored in database is 
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="options">
            <language index="lDEF">
                <field index="settings.links">
                    <el index="el">
                    </el>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```

Only removing the `<field...</field>` value makes the PHP warning go away.

**Comment by jmverges** [comment]
duplicated by: https://github.com/FluidTYPO3/flux/issues/973

**Comment by jmverges** [comment]
fixed by: https://github.com/FluidTYPO3/flux/pull/996
