### ISSUE TITLE
Container with restricted FCEs:  Fluid Content type dropdown not filtered

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#300]
I've got a container element with a grid column that allows only a single type of elements.

When editing this element, the field "Type" and "Fluid Content type" contain types that are not allowed by the container:

![2015-11-05 fluidcontent edit restricted](https://cloud.githubusercontent.com/assets/59036/10965335/8d56b3d8-83ac-11e5-968e-0883736c9866.png)

The type and fluid content type dropdowns should be filtered to the allowed values.

**Comment by cweiske** [comment]
@coding46: I get the following error when editing or creating elements on a place without a filter:

>  #1: PHP Catchable Fatal Error: Argument 1 passed to FluidTYPO3\Flux\Provider\AbstractProvider::getViewContext() must be of the type array, null given, called in .../typo3conf/ext/fluidcontent/Classes/Backend/ContentSelector.php on line 175 and defined in .../typo3conf/ext/flux/Classes/Provider/AbstractProvider.php line 270

The "Fluid Content Type" dropdown is filtered if there is a whitelist. (But the "Fluid Content Type" top entry is still there). The "Type" dropdown is not filtered.

**Comment by coding46** [comment]
As it's WIP, those things happen. Thanks for reporting.

**Comment by NamelessCoder** [comment]
Filtering implemented via new `processTableConfiguration` method on Flux Providers. In addition, the Fluid Content type selector is now more standardised TCA. See also https://github.com/FluidTYPO3/fluidcontent/issues/317 which is related to the *rendering* of the mentioned fields.
