### ISSUE TITLE
Crash with <f:link.typolink> in Preview section: Call to a member function getPage_noCheck() on null

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#301]
When I use `<f:link.typolink parameter="settings.link">foo</f:link.typolink>` in the preview section with a field that has an internal page ID set as URL (e.g. "45"), then I get a crash:

> Fatal error: Call to a member function getPage_noCheck() on null in .../typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php on line 6094

**Comment by cedricziel** [comment]
`<f:link.typolink>` is a core ViewHelper we have no control over. 

EXT:frontend has no context in the backend.

**Comment by cweiske** [comment]
So what does this mean now?
Should I report a bug on forge.typo3.org?

**Comment by cedricziel** [comment]
This basically means: This is the wrong place to report it :)

Actually I don't think this will get fixed in core nor that you should place active links in the preview section.
If you know what you're doing, you can implement a custom ViewHelper that uses a custom rendering to your liking.

**Comment by cweiske** [comment]
I've opened a bug report for fluid: [Bug #71361: fluid link.typolink crashes in Backend with page links](https://forge.typo3.org/issues/71361).

**Comment by cedricziel** [comment]
Though I think this is a very bad idea - Good luck an thx for reporting.

**Comment by cweiske** [comment]
Maybe a backend link view helper could be used if there was one. One that switches pages in the backend.

**Comment by cedricziel** [comment]
That's something you can easily do on your own as the apis for tokens are available in the backend context. Overall i think this makes much more sense than un-guarding typolink from all the security measures it originally implicilty uses through the request context. Navigation through the backend with permalinks in the elements sounds unorthodox yet cool :)

**Comment by cweiske** [comment]
I'm also thinking about frontend editing which really would be better when links are rendered.
