### ISSUE TITLE
ACL: Only one allowed element is saved

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#317]
When trying to white-liste two or more elements for a backend group, only one of the selected content elements is saved in `tx_fluidcontent_allowedfluidcontent`.

Refs bd9a0e8c4362b42f833f174a08d43383bce03096 and #282.

**Comment by NamelessCoder** [comment]
What the.... okay that's weird, but I know why I didn't detect it while creating the feature - I only tested with a single element. No clue why it saves just one, but I'll investigate.
