### ISSUE TITLE
[DOC] Easy Printable Download Version of Templating Guide

### ISSUE THREAD

**Issue by al-Iskandar** [FluidTYPO3/fluidcontent#320]
It would be nice if you would offer a easy printable download version of the templating guide (https://fluidtypo3.org/documentation/templating-manual/introduction.html) in one document (e.g. pdf). So it would be possible to print out the tutorial for concentrated reading into the new topic.

**Comment by NamelessCoder** [comment]
Thanks for suggesting this, @al-Iskandar - but we have to focus our efforts elsewhere and perhaps some day find a utility that can render our docs as PDF or whichever other format is preferred.

Until that day there are a few options you can use depending on the quality of static output you want:

* There's a utility called `grip` (it's a python application) that renders Github markdown as various formats; that one can among other things make a static HTML with navigation.
* You can convert individual chapters using any Markdown application (basic support) or `grip` (full support) and then concatenate those into a proper document.
* You can do a recursive `wget` on everything below https://fluidtypo3.org/documentation/templating-manual/ and keep that as static HTML with navigation, in our design.

Hope that helps ;)
