### ISSUE TITLE
Wrong fluid content type in select box

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/fluidcontent#326]
I'm using a simple content element with flux:field.inline.fal-ViewHelper. Don't know exactly how to reproduce the bug, but after re-arranging the position of a fal-record by editing, fluidcontent fails to display the right fed_fcefile-type and selects the wrong content element type-value in the edit-page content-select box. Like issue #226.

The plugin options instead have the correct type, but then are saved with the wrong type.

TYPO3 6.2.15
fluidcontent: 4.2.0

**Comment by webloft** [comment]
I see this bug was fixed in 4.2.1.

**Comment by NamelessCoder** [comment]
Thanks for following up, @webloft - seems we forgot to link the fix with the issue.
