### ISSUE TITLE
Class ext_update in global namespace

### ISSUE THREAD

**Issue by SomeBdyElse** [FluidTYPO3/fluidcontent#330]
The Class `ext_update`, defined in `class.ext_update.php` is in the global namespace and conflicts with the same class in flux. Yet, the content of the two classes differs.

**Comment by NamelessCoder** [comment]
This is unfortunately how TYPO3 requires extension update scripts to be delivered. As soon as an alternative option becomes available we will of course start using that. But until that time we are forced to put the class file there and name the class exactly that way.
