### ISSUE TITLE
auto update from flux to 7.3.0 when installing fluidcontent

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/fluidcontent#331]
hello,

i have a problem when installing fluidcontent:

typo3 6.2.14
php 5.4

i have flux 7.2.1 installed

then i want to install fluidcontent 4.2.1

while installing this (via extension manager or t3x file), my flux is automatically updated to 7.3.0 (!) which does not work with my typo3 version!

why does this happen?

best regards
blueamerican

**Comment by blueamerican** [comment]
ext_emconf.php from fluidcontent 4.2.1 shows the right dependent flux version:

flux' => '7.2.0-7.2.99',

but why this automatic uodate to flux 7.3.0?

**Comment by NamelessCoder** [comment]
Hi Markus,

This should not happen. It does sound suspiciously like an error of the extension manager; specifically that it tries to use the constraints from the most recent version *also* when you explicitly install an older version. But that's a guess on my part.

Please report this one to the TYPO3 bug tracker - it might also be an issue in the new LTS. But I would not expect it to be fixed for 6.2 (maybe in the extended support one though).

You can however work around this one if you install dependencies using composer (which will surely restrict these versions even if EM does not) - and you can bypass EM's install logic by using the CLI command of TYPO3 to do `extension:install flux` etc. after you've uploaded or pulled the extension folders manually.

**Comment by blueamerican** [comment]
I found out that the Extension Manager error only occurs in development setting.
I made a an issue at typo3 forge
