### ISSUE TITLE
[question] Why is fluidcontent_content shown as of type form?

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/fluidcontent#336]
Is there a special reason for displaying fluidcontent_content content type in optgroup "Forms"?

![fluidcontent](https://cloud.githubusercontent.com/assets/116824/12351552/9dd5eae4-bb7e-11e5-87ac-2f4c0461b757.png)

**Comment by NamelessCoder** [comment]
Honestly I'm not sure. The groupings here come from a magic naming of items using `--groupname--` and label reference as key/value pair but I don't know why they'd get sorted this way. Does the same thing happen when registering *any* (Extbase) plugin as content type? If so, I'd call that a core bug (perhaps best solved by creating a new group or allowing the group name to be configured when registering the plugin/CType).

**Comment by fnagel** [comment]
> Does the same thing happen when registering any (Extbase) plugin as content type?

Not sure if that is the case, but it's an interesting question. I just wondered if this the current location was done on purpose as it seems unfitting.

Thanks for the response!
