### ISSUE TITLE
Workspaces: Fail to create new element after workspace-only element in fluidcontent container

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidcontent#339]
It's not possible to create a new content element _after_ an element that is available in the workspace only, within a fluidcontent container.

Steps to reproduce:
1. Create a workspace in TYPO3
2. Create a fluidcontent element that takes child elements (a container, with `<flux:grid.column>`)
3. Put container element on a page
4. Switch to workspace
5. Create child element to that container
6. Click the "+ Content" icon after the element created in step 5
7. Exception: `#1437656456: $uid must be positive integer, -1 given`

**Comment by xmaxw** [comment]
I have the same issue (TYPO3 7.6.9 + flux 7.4.0 + fluidcontent 4.4.1)

**Comment by NamelessCoder** [comment]
Solved by recent Flux release - fluidcontent release will follow soon.
