### ISSUE TITLE
Insert record doesn't work with news

### ISSUE THREAD

**Issue by avionbg** [FluidTYPO3/fluidcontent#340]
Insert record (shortcut) isn't working with "tx_news" extension, probably other fluid based extension have issues too. 

I've tested the extension with css_styled_content and it's working but no matter what configuration I enter it's no use.

**Comment by NamelessCoder** [comment]
Belongs to `fluidcontent_core` but confirmed; shortcuts can only be made to actual content elements - `fluidcontent_core` is not and cannot become able to render TS objects the same way `css_styled_content` does (and that's not really the intention either).

The right way to do this - also regarding the level of control you will have over how the news item is displayed - is to insert a news detail plugin; in a column that doesn't get rendered if necessary. Then make your shortcut target that plugin.
