### ISSUE TITLE
Generate a link to edit the CE

### ISSUE THREAD

**Issue by enilee** [FluidTYPO3/fluidcontent#341]
I can´t create a link like the typo3 "edit link" with Fluid.
I would wrap my preview content with this link.

Example:

`<f:section name="Preview">
     <a href="LINK_TO_EDIT">
        <strong>Website Foo:
            {headline -> f:format.nl2br()}
        </strong>
    </a>
</f:section>
`

**Comment by NamelessCoder** [comment]
Hi @enilee - how the link should be generated completely depends on your TYPO3 version. I'm sorry to say there are no ViewHelpers which can consistently get you that result, so the best you can do is take a look at _another_ editing link that TYPO3 generates in your site and hardcode that as URL in your Preview sections link, then insert/replace the "pid" and "uid" values and whichever other parts you may need to change (this depends on the TYPO3 version).
