### ISSUE TITLE
Unwanted validation of inputfields with TYPO3  7.6.5 

### ISSUE THREAD

**Issue by ThomasWaw** [FluidTYPO3/fluidcontent#346]
Hi,
I have a FCE with an Input-field suposed to hold a Number. Its defined as:
`<flux:form id="stageTeaser" options="{group: 'FCE'}">`
`<flux:field.input name="price" label="Preis" />`

When I enter only a number in this input field - TYPO3 doesn't allow my to save the element. I can save it when I enter an alphanumeric string, but not a single number.
   
TYPO3 7.6.5
fluidcontent 4.4.0

**Comment by NamelessCoder** [comment]
Hi Thomas,

This is fixed in the `development` branch of Flux and will be included in the next TER version. The problem was unintentional adding of `range` definitions in generated TCA causing FormEngine to apply the incorrect validation.

**Comment by ThomasWaw** [comment]
Hi NamlessCoder,
- thanks a lot. I'll check it. 
maybe it is rather a flux-issue than a fluiedcontent-issue anyway?!
