### ISSUE TITLE
iconIdentifier not found in mod.wizards.newContentElement.wizardItems 

### ISSUE THREAD

**Issue by monosize** [FluidTYPO3/fluidcontent#348]
After Commit https://github.com/FluidTYPO3/fluidcontent/commit/e945a1d36eab1d1a93737761c6dbd4594435b058 there are no icons shown in the newContentElement.wizard. (see Screenshot) 

![image](https://cloud.githubusercontent.com/assets/1583746/14642039/3062be04-0649-11e6-86ac-3865d4feeeb8.png)

The IconRegistry is called only during the build of the PageTSConfig. When pageTsConfig is loaded from the cache, then the icons are not registered. see ```buildWizardTabItem in ConfigurationService```

**Comment by blueamerican** [comment]
i can confirm this.

in typo3 7.6.2, flux 7.3 (development), fluidcontent 4.4.1 several ways of embedding the icon ends in:

<img width="32" height="32" src="/www/pathtoserver/htdocs/project/typo3conf/ext/my_templates/Resources/Public/Icons/Content/Example.svg">

a broken image

**Comment by NamelessCoder** [comment]
Fixed in `development` and `legacy` branch even contains a workaround which was kindly sponsored by **dkd**, http://www.dkd.de/.
