### ISSUE TITLE
[ Typo3 7.6.6 + Fluidcontent 4.4.1 ] Backend just breaks

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/fluidcontent#351]
This is the error message I get

```
#1320585902: $hookObject "FluidTYPO3\Fluidcontent\Backend\TableConfigurationPostProcessor" must implement interface TYPO3\CMS\Core\Database\TableConfigurationPostProcessingHookInterface (More information)

UnexpectedValueException thrown in file
/var/www/thl/htdocs/typo3_src-7.6.6/typo3/sysext/core/Classes/Core/Bootstrap.php in line 1022.
```

Any idea?

**Comment by julianxhokaxhiu** [comment]
Commenting out https://github.com/FluidTYPO3/fluidcontent/blob/development/ext_localconf.php#L23 fixes the issue, but I have no idea what this implies.

**Comment by NamelessCoder** [comment]
Disabling that line is likely to cause issues with TCA and/or the ACL for allowed types. The class in question *does* implement the right interface so I'm not sure why your TYPO3 says it doesn't.

**Comment by julianxhokaxhiu** [comment]
Honestly I have no idea. Fresh install with all the latest code from your git ( just git cloned all the development branches like 10 mins before creating the issue ),

If I enable that line now again it still gives that error.

**Comment by NamelessCoder** [comment]
Will have to close this one, and conclude that the PHP interfaces are indeed compatible and do not break on any of our supported PHP versions. If something is causing another interface to be loaded I am unfortunately not aware of *what* might be doing it (if, as you say, you don't use `compatibility6` - which is my only suspect).

The only code that consumes the line you comment out (besides what `compatibility6` might do - I don't have any experience at all with it) is Bootstrap->runExtTablesPostProcessingHooks and the consumption is pretty straight-forward. The hook class itself is also very simple, no subclasses, just the interface implementation and an extremely simple delegating method to add page TS config. Class loading is done with getUserObj which should perfectly support the passed class reference on any TYPO3 version.

If you do locate the actual cause we're happy to hear about that. Currently only you and Markus seem to have experienced it and Markus' issue went away so it's only you that I know of now.
