### ISSUE TITLE
7.6.6 and fluidcontent 4.4.1 dev branch

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/fluidcontent#352]
Hi,

after installing fluidcontent dev branch by ftp upload and installing it by extensionmanager into a virgin TYPO3 7.6.6 installation I get the following error that breaks the backend:

#1203699034: A cache with identifier "fluidcontent" does not exist. (More information)

TYPO3\CMS\Core\Cache\Exception\NoSuchCacheException thrown in file
/html/typo3/typo3_src-7.6.6/typo3/sysext/core/Classes/Cache/CacheManager.php in line 126.

**EDIT: Sorry, now it is the error like the issue #351 Now I get the same error message!**

As a workaround I can first install fluidcontent by TER and then I overwrite it by the dev branch. That is working.

Greetings 
Markus

**Comment by NamelessCoder** [comment]
Hi Markus,

In that case, I will close this issue and continue in https://github.com/FluidTYPO3/fluidcontent/issues/351 (which you can click "subscribe" to if you want to be advised of updates).
