### ISSUE TITLE
Simple input field is rendered invalid if it contains only numbers

### ISSUE THREAD

**Issue by ervaude** [FluidTYPO3/fluidcontent#353]
Hey, I have some fluidcontent elements with sections that contain fields like this: `<flux:field.input name="title" />`. A simple input field. In TYPO3 7.6 I cannot enter "numbers only" in those fields. An input field that contains only numbers is rendered invalid by the FormEngine Validation.

Can you confirm this or tell me what I am doing wrong?

Usecase is e.g. a link wizard

 ```
<flux:field.input name="link">
     <flux:wizard.link/>
</flux:field.input>
```

If you select a page, then only the ID is inserted in the input field. It is invalid and though cannot be saved.

Any ideas?

**Comment by bjo3rnf** [comment]
Please see https://github.com/FluidTYPO3/flux/issues/1116

**Comment by ervaude** [comment]
Thank you for the link, seems solved in the next release. I'll close this!
