### ISSUE TITLE
Icons missing in list and page module

### ISSUE THREAD

**Issue by Kitzberger** [FluidTYPO3/fluidcontent#361]
I'm almost certain this issue already exists in this pool but still I do not seem to be able to locate it. There are quite a few issues regarding missing icons in the content wizard but none (?) for missing icons in list and page module. I'm a little confused about this whole icon topic when I'm honest.

Fluidcontent is supposed to register the icon that I'm form.option.icon'ing with the new IconAPI, right? As I understand it, that's how the content wizard icon is implemented by now. When no icon is provided, a black Plugin.svg from this extension is used. This part works as expected.

In list module there's no icon visible at all for our custom fluidcontent elements, seemingly due to a css that flux attaches to the backend: https://github.com/FluidTYPO3/flux/blob/7.4.0/Resources/Public/css/icon.css#L8

When removing this `opacity:0` the generic icon for the custom fluidcontent elements (apps-pagetree-root.svg) is being displayed again.

Is it possible to use the form.option.icon'ed file as the icon in the list and page module as well?

We're using TYPO3 7.6.9 and the current TER version of fluidcontent and flux.

Thanks for your time!

**Comment by nannione** [comment]
I agree, this error is still persistent in 7.6.10

**Comment by Kitzberger** [comment]
The best results so far (new content element wizard **and** Fluid content type dropdown) am I getting with hardcoding the path to the icon file like this

    <flux:form.option.icon value="/typo3conf/ext/custom_ext/Resources/Public/Images/Backend/MyFCE.png" />

instead of using the viewhelper `v:extension.path.resources` to get an relative path to the file. The latter only show an icon within the new content element wizard **but not** in the fluid content type dropdown when editing the element.

Either way the icons won't show up on list and page module. And the generic fluidcontent icon (black TYPO3 logo) will only show up when removing that line mentioned in icon.css from flux.

Is it even possible to show the FCE icon in list and page module?

**Comment by NamelessCoder** [comment]
I would suggest putting your icon files in `Resources/Public/Icons/Content/$nameOfTemplate.$format`, e.g. `Resources/Public/Icons/Content/MyFCE.png` in your case, assuming your FCE template's filename is `MyFCE.html`. This should work in all current versions on all supported TYPO3 versions (and performs better than customising this path in your Flux forms).

**Comment by Kitzberger** [comment]
@NamelessCoder Thanks for the hint. This actually did the trick!

As a side note: in a different project (using the very same setup and same versions of TYPO3, flux, fluidcontent) customizing the path worked in most cases.

Anyway, we're gonna switch to the convention which seems to cover all scenarios.
