### ISSUE TITLE
Slow backend

### ISSUE THREAD

**Issue by sunet3cms** [FluidTYPO3/fluidcontent#362]
Hi 

I'm running a Typo3 7.6.11 website with a basic provider extension using flux grid. The problem is, that the backend is really slow with larger sites. It seems that the backend typoscript is parsed on every request, and even pages with only 2 content elements have loadtimes above 5 seconds. I tried installing the fluidcontent dev version, that raises backend loadtimes to around a minute or so. In the database table cf_fluidcontent, the blob is around 500kb. And if i change backend layout under apearance to none or uninstall fluid, fluidcontent, fluidpages, flux, vhs and my provider extension, the backend in general is about 5 times faster.

**Comment by sunet3cms** [comment]
This is the call from network that seems to be really slow:
index.php?M=web_layout&moduleToken=2f1a49ceb1ac3ad3c4960c00ed000150ab6e26a6&id=3

**Comment by cedricziel** [comment]
The URL you provided is the web-module itself, if you think the serialization is slow, then you could swap the cache backend for the cache configuration `fluidcontent` to be of type `NullBackend`.

**Comment by morinfa** [comment]
Not sure it's related, but I've noticed that backend pages are loaded twice when FluidContent extension is enabled.

Exemple, when I click on the root page, in page view :
```
GET http://localhost/typo3/index.php?M=web_layout&moduleToken=9802746a9675fbb84194720888c77ae8613f5d7b&id=3
POST http://localhost/typo3/index.php?ajaxID=%2Fajax%2Fext-direct%2Froute&namespace=TYPO3.ExtDirectStateProvider (XHR)
GET http://localhost/typo3/index.php?M=web_layout&moduleToken=9802746a9675fbb84194720888c77ae8613f5d7b&id=3
```
When FluidContent extension is disabled, the second GET request is not done.
```
http://watches2016/typo3/index.php?M=web_layout&moduleToken=9802746a9675fbb84194720888c77ae8613f5d7b&id=3
POST http://watches2016/typo3/index.php?ajaxID=%2Fajax%2Fext-direct%2Froute&namespace=TYPO3.ExtDirectStateProvider (XHR)
```
This second GET request slows down the backend a lot (each GET request takes around 3 seconds on my computer).

**Comment by NamelessCoder** [comment]
Solved (in Flux) by remembering and reusing the TS setup after parsing once.

**Comment by provitex** [comment]
We have the same problem. Can you explain how to fix it?
We use TYPO3 7.6.16 with Flux 7.4.0

**Comment by NamelessCoder** [comment]
Update Flux to at least version 8.1.0 to obtain the mentioned fix.
