### ISSUE TITLE
format.html - Links in backend preview

### ISSUE THREAD

**Issue by abelokon** [FluidTYPO3/fluidcontent#363]
I created a content element with a RTE field via flux.
The issue I have is that links inserted from RTE are not visible in the backend preview when the content is parsed with f:format.html.

**Comment by NamelessCoder** [comment]
This is a TYPO3 core issue and I'm afraid there is nothing we can do about it on our side. For more information you can see the core bug report: https://forge.typo3.org/issues/66855.
