### ISSUE TITLE
Label failes if add content element to Tab "common" in NewContentElementWizard

### ISSUE THREAD

**Issue by Lagerregal** [FluidTYPO3/fluidcontent#364]
Hey there,
I found a bug while adding a content element to an existing tab from the core, like "common".

``` html
<flux:form id="foo" options="{group: 'common'}" />
```

The tab has now the title "**common**" instead of "**Typical page content**". 

The reason is the following:
In the function `\FluidTYPO3\Fluidcontent\Service\ConfigurationService->buildAllWizardTabGroups()` is a check if the label could be found here in `LLL:EXT:backend/Resources/Private/Language/locallang_db_new_content_el.xlf`.
But this does not work because the language handling `$GLOBALS['LANG']` is not loaded at this point.

Maybe we should add a workaround like this:

``` php
if (!is_object($GLOBALS['LANG'])) {
    $GLOBALS['LANG'] = GeneralUtility::makeInstance(\TYPO3\CMS\Lang\LanguageService::class);
    $GLOBALS['LANG']->init($GLOBALS['BE_USER']->uc['lang']);
}

[...] // do our translation stuff now

unset($GLOBALS['LANG']);
```

Background:
In the method `\TYPO3\CMS\Backend\Http\RequestHandler->boot()` is fluidcontent loaded with the call `loadExtensionTables()` and the language handling is called later with `initializeLanguageObject()`

**Comment by DavidCzadilek** [comment]
I can confirm this for fluidcontent v4.4.1 running on TYPO3 8.5.
Any reason not to use @Lagerregal's proposed solution?
