### ISSUE TITLE
The property "options.Fluidcontent.sorting" on the subject was not accessible.

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/fluidcontent#376]
line 303 in ConfigurationService.php
            `$formSet = $this->sortObjectsByProperty($formSet, 'options.Fluidcontent.sorting', 'ASC');`
leads to the given error message.
I tried to set 
		`<flux:form id="something" options="{Fluidcontent: {sorting: 100}}">`
as stated here: https://github.com/FluidTYPO3/fluidcontent/issues/181
but I still get the error. I debugged it down to Extbase\Reflection\ObjectAccess but there's no handling of (nested) strings like this. The method expects a single property name.
The given object $formSet has the property 'options' as nested array options[Fluidcontent][sorting]=100

**Comment by pwodaniilea** [comment]
This happens for me in Typo3 8.5.1, fluidcontent 4.4.1, flux 8.0.0.
It occurs when I create more than one fluidcontent element definition.

**Comment by geldmacher** [comment]
I can confim this in 7.6.15, fluidcontent 4.4.1 and flux 8.0.0.

If you comment out line 277 in luidTYPO3\Fluidcontent\Service\ConfigurationService it is "hotfixed".

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/flux/pull/1283 but still not released (working on a few more bug fixes before TER release - safe to use development branch of flux until then).
