### ISSUE TITLE
 Cannot declare class FluidCache_XZY_Content_action_swiperheader

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/fluidcontent#381]
I have a small issue with content elements made up of more than 1 word.
I'm talking about elements created with fluidcontent. I am using TYPO3 7.6.15 and the latest versions of flux and fluidcontent.

For example, I have a Content template called SwiperHeader.html, with an empty action called swiperHeaderAction() defined inside the Content controller.
```
use FluidTYPO3\Fluidcontent\Controller\ContentController as AbstractController;

class ContentController extends AbstractController {

    public function swiperHeaderAction() {
    }
```

After I upraded to the latest version of fluidcontent and flux I am getting an error in the backend that my class already exists.

SwiperHeader  generates 2 files in typo3temp, and thus 2 classes with the same name (since PHP ignores case for class names)
XYZ_Content_action_swiperheader_dbb02c00f42a8c1034792fcb6e9d8db3d655f62c.php
and
XYZ_Content_action_swiper**H**eader_dbb02c00f42a8c1034792fcb6e9d8db3d655f62c.php
Note the case difference for the letter H, in both examples. So fluid, flux or typo3 (haven't yet figured out which one exactly) generates 2 classes for the different cases.

For fluidcontent elements made up of only 1 word (eg: Video) it works just fine, I see only one 
HXY_Content_action_video_7625b2bc1f82b79797bd8296331baff946e17d25.php

Is this a bug or do we need to setup some new setting in the latest version of flux/fluidcontent to prevent the generation of multiple classes for the same element?

I can edit my element, but whenever I save the element I get this error, if I clear the cache it works till the next time I save/edit it.

**Comment by NamelessCoder** [comment]
This one is solved on `dev-development` and will be fixed in release 8.0.1 - which will be released probably today.
