### ISSUE TITLE
fluidcontent not working after update to typo3 8.7

### ISSUE THREAD

**Issue by oliverbeck** [FluidTYPO3/fluidcontent#406]
Hi

I've just upgraded an installation (typo3 6.2, fluidcontent 4.0) to typo3 8.7 and fluidcontent 5.2. Now I get 2 errors: The Frontend throws:

#1257246929: Tried resolving a template file for controller action "Content->render" in format ".html", but none of the paths contained the expected template file (). The following paths were checked

If I try to edit an existing fluidcontent element the Backend throws:

#1476107295: PHP Warning: is_file(): open_basedir restriction in effect. File(/path/to/webroot/..) is not within the allowed path(s): (/path/to/webroot/:/tmp/) in /path/to/source/typo3_src-8.7.1/typo3/sysext/backend/Classes/Form/Utility/FormEngineUtility.php line 126

I ran the update script, but it didn't affect any rows.

Kind regards, Oliver

**Comment by meronimo** [comment]
https://wiki.typo3.org/Upgrade

> 
> Stepwise upgrade: You must use TYPO3 7.6 or newer before you upgrade to TYPO3 8.7 LTS! Therefore please upgrade from 6.2 to 7.6 first, then from 7.6 to 8.7 LTS. This involves running the LTS to LTS update wizard (see above), then the new 7.6 to 8.7 upgrade wizard. Plugins should be updated to the latest 7.6 compatible version first, then to the 8.7 version after the second upgrade. Note that the second upgrade is faster than the first!
> 
> You need PHP 7 at least for 8.7!

Did you upgrade from 6.2 to 8.7 or stepwise?

**Comment by oliverbeck** [comment]
Hi VancD

Sorry, I didn't mentioned but I've upgraded stepwise 6.2 -> 7.6 -> 8.7

**Comment by oliverbeck** [comment]
Any ideas?

**Comment by fnagel** [comment]
Just a wild guess but check upper / lowercase of your template files and make sure to update your template / partial / layout TS config.

**Comment by NamelessCoder** [comment]
The error suggests a problem with your TS and/or the template paths you defined in TS. You may need to do additional migration such as use the new `templateRootPaths` naming - your starting version of TYPO3 is low enough that it is likely your TS contains the old `templateRootPath` naming.

Finally, make certain that any paths you defined actually do not exist without the base dir restriction (which you did not say, but if you added that restriction or upgraded PHP to a new version and had that restriction added as default, then of course all your template paths - and that includes symlink targets if you're using symlinks - must exist within the base dir defined in PHP).

**Comment by NamelessCoder** [comment]
`development` branch is now 8.7-compatible, but a TER release has not yet been made. Note that you'll also need a 8.7-compatible version of Flux (and if you try the `development` branch you will also need to use the `development` branch from Flux until the TER releases are made).
