### ISSUE TITLE
Superfluous p-tags in RTE enabled textfields after save

### ISSUE THREAD

**Issue by derhansen** [FluidTYPO3/fluidcontent#407]
When you use the RTE (ck_editor) in textfields of fluidcontent elements, superfluous p-tags are saved to the RTE fields while saving the element.

Steps to reproduce.

1. Create a simple fluidcontent element with just one field (`<flux:field.text name="test" enableRichText="true" label="Test" />`)
2. Add the new element to a TYPO3 page and enter text into the RTE. As an example, enter "Test1", "Test2", and "Test3" separated by a new line

The content before the save process is as following:
```
<p>Test1</p>

<p>Test2</p>

<p>Test3</p>
```

3. Save the content element. The contents of the RTE field now contains superfluous p-tags as shown below

```
<p>Test1</p>

<p>&nbsp;</p>

<p>Test2</p>

<p>&nbsp;</p>

<p>Test3</p>
```

RTE fields from TYPO3 content elements and RTE fields of TYPO3 extensions does not show this behavior.

I'm using TYPO3 8.7.1 with fluidcontent 5.2.0 and all other FluidTYPO3 related extensions up2date.

**Comment by NamelessCoder** [comment]
I'm pretty sure this isn't a Flux issue and that saving an RTE text field that's configured the same way, but exists in an oldschool FlexForm DS, would produce the same problem. Flux does no post-processing of the *value* when saving, so if it gets put into the DB, it was put there either by the JS-part of the CK editor or by how TYPO3 handles the input for those fields (which in turn may be affected by things like your pageTSconfig settings for sanitizing RTE).

But, there's all likelyhood this is not related to Flux. All we do is hand TCA over to TYPO3 and it then does the rest.

**Comment by derhansen** [comment]
I tested the whole scenario now in blank TYPO3 8.7 website without any special configuration regarding the ck_editor. Also the site setup is really simple and TS setup only contains a simple `FLUIDTEMPLATE` object with one template.

I created a simple Plugin with a FlexForm that contains the following field:

```
<myField>
    <TCEforms>
        <label>TEST</label>
        <config>
            <type>text</type>
            <cols>48</cols>
            <rows>5</rows>
            <enableRichtext>1</enableRichtext>
        </config>
    </TCEforms>
</myField>
```

When I enter the same 3 test-lines, the Data is saved correctly and the Superfluous p-tags do not occur.

I then did some more debugging in the TYPO3 DataHandler.

## Input from own Plugin with Flexform (shortened)

**Incoming:**
`vDEF => '<p>Test1</p> <p>Test2</p> <p>Test3</p> '`

**Transformed XML:** 
`<value index="vDEF">&lt;p&gt;Test1&lt;/p&gt; &lt;p&gt;Test2&lt;/p&gt; &lt;p&gt;Test3&lt;/p&gt;</value>`

**Value in Database:**
```
<value index="vDEF">&lt;p&gt;Test1&lt;/p&gt;
&lt;p&gt;Test2&lt;/p&gt;
&lt;p&gt;Test3&lt;/p&gt;</value>
```
## Input from FluidContent Flexform (shortened)

**Incoming:**
`vDEF => '<p>Test1</p> <p>Test2</p> <p>Test3</p> '`

**Transformed XML:** 
`<value index="vDEF">&lt;p&gt;Test1&lt;/p&gt; &lt;p&gt;Test2&lt;/p&gt; &lt;p&gt;Test3&lt;/p&gt;</value>`

**Value in Database:**
```
<value index="vDEF">&lt;p&gt;Test1&lt;/p&gt;

&lt;p&gt;Test2&lt;/p&gt;

&lt;p&gt;Test3&lt;/p&gt;</value>
```

Note, that the values saved to the database for FluidContent contains _2 blank lines_. The RTE ck_editor will render those blank lines as `<p>&nbsp;</p>` and after you safe the element another time, the `<p>&nbsp;</p>` is present in the database including another blank line.

I have debugged it all down to the `updateDB` method in the TYPO3 DataHandler and obviously the incoming XML in the field `pi_flexform` seem to have the same structure without the blank lines.

Any idea where the blank lines could be added (maybe an invisible char somewhere?) and why it only happens for content from `fluidcontent` extension?

**Comment by keinereiner** [comment]
we have the same problem too

**Comment by monosize** [comment]
maybe old RTE stuff in the RTE configuration?
see https://forge.typo3.org/issues/80720

**Comment by keinereiner** [comment]
empty project... there is no old configuration.... The RTE ck_editor will render blank lines after you safe the element another time.

**Comment by olegkarun** [comment]
@keinereiner  the same in my custom FLUID CE i use `<flux:field.text name="text" label="Text"                        enableRichText="TRUE"/>` and every time when i save text i get new line `<p></p>` after each paragraph.
But when i use standart fluid_styled_content - all good

TYPO3 8.7.1 + FLUX 8.2.1

**Comment by kimchristiansen** [comment]
TYPO3 8.7.4 + flux 8.2.1 is still having this issue.

**Comment by NamelessCoder** [comment]
Fixed in dev-development - please have patience while we prepare for new releases.

**Comment by BKapelari** [comment]
Same problem here! Please update!

**Comment by ChristianHoefer** [comment]
@NamelessCoder where can i find this Fix, still same Issue on 5.2.0 and Development

**Comment by NamelessCoder** [comment]
Fix is related to flux so you need flux dev-development. The issue was misplaced in the fluidcontent bug tracker.

**Comment by pixelplant** [comment]
I have issues using flux-dev, as fluidpages and fluidcontent need to also be updated to their dev version, which breaks functionality on my site.
For those looking just for the changes to apply to flux, grab it from here: https://github.com/FluidTYPO3/flux/commit/00100eee7ea4c6386ec0ab297a5c23fef3689962

**Comment by NamelessCoder** [comment]
Are the issues you experience already reported as issues to the various repositories? If not, would you mind doing that? We depend on user feedback to catch issues before releases.

**Comment by dev65** [comment]
Update with latest DCE version and set configration
<config>
	<type>text</type>
	<rows>5</rows>
	<cols>30</cols>
	<eval>trim,required</eval>
	<enableRichtext>1</enableRichtext>
</config>

**Comment by gaurisabhadiya** [comment]
Update with DCE with latest version, and use following configuration.
`

<config>

	<type>text</type>

	<rows>5</rows>

	<cols>30</cols>

	<eval>trim,required</eval>

	<enableRichtext>1</enableRichtext>
</config>


`

**Comment by NamelessCoder** [comment]
@gaurisabhadiya Thanks for the update - but this issue tracker is about Fluidcontent, not DCE (and this issue was misplaced, it belongs in Flux). The problem in Flux was solved quite a while ago so this issue is closed.
