### ISSUE TITLE
Exception: Argument "renderMode" was not registered.

### ISSUE THREAD

**Issue by spackmat** [FluidTYPO3/fluidcontent#409]
Hi,

I am new to FluidTYPO3 and I am now trying to implement my first content element [as described in the documentation](https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/content-element.html). Despite the funny fact, that I had to find out that new content elements only show up in the New Content Wizzard, when one performs a full cache wipe within the install tool, I cannot get the example `Teaser.html` content element to work:

When I try to create it in the New Content Wizzard, I get an Exception of Fluid: "Argument "renderMode" was not registered." This happens with all content elements I tried, even with the `Example.html` created by the Builder extension.

My Setup:

- PHP 7.1.5
- A freshly installed TYPO3 7.6.18
- fluidbackend	1.1.0
- fluidcontent 5.2.0
- fluidcontent_core 1.4.0
- fluidpages 4.1.0
- flux 8.2.1
- vhs 4.2.0
- builder 1.2.0

Am I missing something? My Provider Extension is freshly created by the Builder.

Greets,
spackmat

**Comment by NamelessCoder** [comment]
Hmm - if you used this template you shouldn't be getting any problems from `renderMode` as it isn't used in the template. Generated templates also shouldn't by default contain any fields that use this argument.

That said: the `renderMode` argument is long gone - when possible, use `renderType` instead (or simply select a different type of component). If you're ever in doubt about which arguments are supported for which ViewHelper, https://fluidtypo3.org/viewhelpers/flux/master.html shows you the ViewHelpers and arguments for the most recent version of Flux.

**Comment by spackmat** [comment]
I did a quick test: Deleted my provider extension and created a new one with the Builder. Installed it as documented and I see the same: when I try to create any content (even the core content elements, I get this Exception. Then I deactivated `fluidcontent_core` and voilà, everything works again. So it seems that fluidcontent_core 1.4.0 is incompatible to the setup, I mentioned in my first post (those versions came yesterday, when I required the extension via composer without specified versions). I don't need fluidcontent_core at all, so my problem is solved. But I can imagine that others need fluidcontent_core and gain the same problem.

Greets,
spackmat

**Comment by NamelessCoder** [comment]
In that case this comes from one or more of the ViewHelpers used in templates from `fluidcontent_core`. If you are not already using it, you must switch to `dev-development` of `fluidcontent_core` and since it is unmaintained, prepare to switch to `fluid_styled_content`.

**Comment by spackmat** [comment]
Oh thanks, good to know fluidcontent_core is unmaintained. I don't need it, so this is not a problem for me.
