### ISSUE TITLE
[TYPO3-8.7.1] Fluid foreach with flux grid.row produces twice as many entries

### ISSUE THREAD

**Issue by Jakobrohlaender** [FluidTYPO3/fluidcontent#411]
TYPO3 Version 8.7.1
PHP Version 7.0.18
Flux Version: 8.2.1
FluidContent: 5.2.0

In the creation of an accordion FCE I am currently experiencing the following problem:

Code (with Debug activated):
![bildschirmfoto 2017-06-20 um 16 25 56](https://user-images.githubusercontent.com/7604024/27340361-956cde92-55da-11e7-8b90-4f4089a9c7b1.png)

1. BE Create a new accordion (3x Elements) & save it
![bildschirmfoto 2017-06-20 um 16 27 39](https://user-images.githubusercontent.com/7604024/27340405-a9cd7144-55da-11e7-8186-b84b05043203.png)
2. Go Back to the Content Page.
Debug output:
![bildschirmfoto 2017-06-20 um 16 26 56](https://user-images.githubusercontent.com/7604024/27340416-af253c12-55da-11e7-9acf-c256334ca405.png)
But I get twice as many entries I created (6):
![bildschirmfoto 2017-06-20 um 16 25 33](https://user-images.githubusercontent.com/7604024/27340435-bc6f1ab4-55da-11e7-946b-5683b6ce2b3a.png)

Looks like a bug for me, does somebody have any idea?

Thanks!

**Comment by monosize** [comment]
@Jakobrohlaender Remove <flux:form.content> in the <flux:grid:column>. This creates the additional entries.

Try this one:  
We use the key as uniqueid -> see https://github.com/FluidTYPO3/flux/issues/1372
```
<flux:grid>
    <f:for each="{contents}" as="contentObject" key='uniqueid'>
        <flux:grid.row>
            <flux:grid.column name="{uniqueid}" label="{contentObject.content.label}"/>
        </flux:grid.row>
    </f:for>
</flux:grid>
```
And remove `<flux:grid />` from the preview section. `<flux:grid>` can only be used in the configuration section.  I think you've confused it with the `<flux:widget.grid>`, but that's obsolete and no longer necessary.

**Comment by Jakobrohlaender** [comment]
Yes, that has solved the problem, thank you very much!
