### ISSUE TITLE
cannot install dev-branch

### ISSUE THREAD

**Issue by fkalka** [FluidTYPO3/fluidcontent#415]
Hi,
i tried to upgrade all FluidTYPO3 Extension to development and i get the following error when i try to install fluidcontent:

`An exception occurred while executing 'SELECT `pid` FROM `sys_template` WHERE (root = 1 AND deleted = 0 AND hidden = 0 AND starttime <= :starttime AND (endtime = 0 OR endtime > :endtime)) AND ((`sys_template`.`deleted` = 0) AND (`sys_template`.`hidden` = 0) AND (`sys_template`.`starttime` <= 1499782980) AND ((`sys_template`.`endtime` = 0) OR (`sys_template`.`endtime` > 1499782980)))': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':starttime AND (endtime = 0 OR endtime > :endtime)) AND ((`sys_template`.`delete' at line 1`

on the next click the following error is shown:
`#1320585902: $hookObject "FluidTYPO3\Fluidcontent\Backend\TableConfigurationPostProcessor" must implement interface TYPO3\CMS\Core\Database\TableConfigurationPostProcessingHookInterface`

All extensions where freshly downloaded from Github.

**Comment by fkalka** [comment]
fluidpages installs fine

**Comment by fkalka** [comment]
I just tried it on a fresh 8.7.3 installation, same result

**Comment by maryisdead** [comment]
Error can be found in `FluidTYPO3\Flux\Service\RecordService->preparedGet()`. It just doesn't bind the parameters and should look like this:

```
public function preparedGet($table, $fields, $condition, $values = [])
{
    return $this->getQueryBuilder($table)->select(...explode(',', $fields))->from($table)->where($condition)->setParameters($values)->execute()->fetchAll();
}
```
Note the `->setParameters($values)` just before `->execute()`.

Unfortunately, after that, I get the following exception:

> Call to undefined method FluidTYPO3\Fluidcontent\Service\ConfigurationService::getViewConfigurationForExtensionName() 

The method simply isn't there. Currenty browsing the repository in hunt of it.

**Comment by maryisdead** [comment]
Ok, the missing method is still in the flux master branch, but marked as deprecated and not present anymore in dev-development: https://github.com/FluidTYPO3/flux/blob/master/Classes/Service/FluxService.php#L313

What is one to use instead?

**Comment by maryisdead** [comment]
Ah well … `getDefaultViewConfigurationForExtensionKey()` deprecated as well. After that a slew of other errors. I give up for today.

**Comment by cweiske** [comment]
`getViewConfigurationForExtensionName()` was removed in commit https://github.com/FluidTYPO3/flux/commit/9a75549fae88946de6bf9efaa28a471aa55996ac for bug https://github.com/FluidTYPO3/flux/pull/1378.

Current `fluidcontent` development branch still uses it, see https://github.com/FluidTYPO3/fluidcontent/blob/development/Classes/Service/ConfigurationService.php#L122

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/fluidcontent/commit/060bf18eeddbd063c218142a5e220eb86b00b629
