### ISSUE TITLE
tx_flux_column not set properly

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/fluidcontent#418]
I cannot save a content elemnt inside a fluidcontent container, because the field tx_flux_column remains empty.

Exactly the same as [here](https://github.com/FluidTYPO3/fluidcontent/issues/382)

TYPO3 8.7.4
fluidcontent 5.2.0
flux 8.2.1

Anybody else with this behaviour?

**Comment by mithri** [comment]
Yes, the problem still persists. Even if the other bug report is closed :-) We have it on several sites.

**Comment by blueamerican** [comment]
i found the the reason: The tab relation and the field tx_flux_column was missing in the TCA of my Content Element

 --div--;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tabs.relation, tx_flux_parent, tx_flux_column

When it works for you, please close this issue

**Comment by SchuBu** [comment]
I don't know if it is a "flux" or a "fluidcontent" problem. But I still have the problem when you drag and drop CE within a Grid-Element.
look at my Issue at: https://github.com/FluidTYPO3/flux/issues/1514

**Comment by NamelessCoder** [comment]
Problem reported in original issue is solved. @SchuBu if you are curious whether this fix solves your problem, please go ahead and try it. Be careful not to cross-post links to your issue from other issues unless you're sure they're related!
