### ISSUE TITLE
Cropping does not take edited picture

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/fluidcontent#425]
I know fluidcontent is obsolete as of now, but we're still using it in a few of our projects. We now noticed on a live project, that FAL images cropping works fine, but when using custom content elements with FAL and we crop fields with the inline editor, the edited image is being ignored.

First set is a default TYPO3 image, the second is our edited with a custom content element. Both have been edited within TYPO3:

![screen shot 2018-06-18 at 1 11 43 pm](https://user-images.githubusercontent.com/3603346/41532915-2eda2c06-72f9-11e8-9c7b-7407a8ecc3ed.png)

That is how the cropping looks, yet it is being ignored by fluidcontent elements:

![screen shot 2018-06-18 at 1 13 16 pm](https://user-images.githubusercontent.com/3603346/41532975-63169dc4-72f9-11e8-8fb4-bce8049f85d9.png)

**Comment by TheNaderio** [comment]
Did you used the image ViewHelper?
Did you added the crop-values to the ViewHelper?
Something like: `<f:image .... crop="{image.crop}" />`

**Comment by MrMooky** [comment]
We ended up with a different solution, but thanks for the help.
