### ISSUE TITLE
Provider Extension for fluidcontent don't overwrite TemplatePaths

### ISSUE THREAD

**Issue by soerenwach** [FluidTYPO3/fluidcontent#432]
Hey there,

I have trouble with the TS overwriting of Templates and Layouts.
I used the Builder Extension to create the extension and used [this](https://github.com/FluidTYPO3/fluidtypo3org/issues/37#issuecomment-309037864) for trying to get it to work.

I'm using:
TYPO3 8.7.19
flux 9.0.1
fluidpages 4.2.0
vhs 5.0.1

My files in the provider Extension (Changed names)

In setup.txt:
```
plugin.tx_fluidfces {
    view {
        templateRootPaths.0 = {$plugin.tx_fluidfces.view.templateRootPaths.0}
		partialRootPaths.0 = {$plugin.tx_fluidfces.view.partialRootPaths.0}
		layoutRootPaths.0 = {$plugin.tx_fluidfces.view.layoutRootPaths.0}
    }
```

In constants.txt:
```
plugin.tx_fluidfces.view {
    templateRootPaths.0 = EXT:fluidfces/Resources/Private/Templates/
	partialRootPaths.0 = EXT:fluidfces/Resources/Private/Partials/
	layoutRootPaths.0 = EXT:fluidfces/Resources/Private/Layouts/
}
```
In ext_emoconf.php in Root $EM_CONF[$_EXTKEY] = array(:
```
'autoload' =>
		array (
			'psr-4' =>
				array (
					'VendorName\\Fluidfces\\' => 'Classes',
				),
		),
```

In ext_localconf.php
```
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('VendorName.Fluidfces', 'Content');
//\FluidTYPO3\Flux\Core::addStaticTypoScript('EXT:tx_fluidfces/Configuration/TypoScript/');
```
The commented line throws an error when its activated. 
Call to undefined method FluidTYPO3\Flux\Core::addStaticTypoScript() 

In ext_tables.php
```
TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile($_EXTKEY, 'Configuration/TypoScript', 'Flud FCEs');
require_once(TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('flux', 'Configuration/TCA/Overrides/tt_content.php'));
```

When I'm trying to using the Classes Controller from the[ link above](https://github.com/FluidTYPO3/fluidtypo3org/issues/37#issuecomment-309037864) I get the following error:
Fatal error: Class 'FluidTYPO3\Fluidcontent\Controller\ContentController' not found in /html/typo3/typo3conf/ext/fluidfces/Classes/Controller/ContentController.php on line 35

When I'm using the example one from the [docs ](https://fluidtypo3.org/documentation/templating-manual/advanced-provider-extensions/custom-flux-controllers/creating-flux-controllers.html)no error shows up but the overwriting still don't work.

I can add the static template to the main Template, but it seems to have no effect on the actual template overwriting.
When I define new constants in the Typoscript with an existing path it doesn't have any effect.

I would be gratefull for any help here.

Thank you very much in advance and best regards,
Sören W.

**Comment by NamelessCoder** [comment]
EXT:builder generates PHP controller classes for Content which extend from the ContentController from fluidcontent, which is now obsolete. Until EXT:builder generates classes correctly again you will need to change the parent class to the ContentController from Flux (replace `Fluidcontent` with `Flux` in the parent class name).

**Comment by soerenwach** [comment]
Thank you for the quick answer. After changing the parent class the error is gone but the TS Overwriting still dont work.

When i check the TS with the ObjectBrowser everything seems to be set, but it doesn't take the Files from the folder. It's still using the templates from the Extension Folder.

Could there be another problem I don't see?

Edit: Even when I change the Folder directly in the setup.txt to a folder in /fileadmin it doesn't work.

**Comment by NamelessCoder** [comment]
Your setup looks correct, assuming you include the TS template in the root TS template that's active on your site. On the other hand it should not be necessary to declare any template paths at all since you are using the default expected template paths.

If you do need to overwrite, I suggest using another index/priority than `0`. It may not solve it, but it is the right way to do overrides since index `0` is reserved for the bottom/fallback paths.

**Comment by soerenwach** [comment]
Thanks for your answer. 
I changed the constants index to 1 but still no changes in the rendering.

But now it seems to work for the fluidpages Provider Extension, but only for the Partials and Layouts Folder. The Templates Folder still uses the typo3conf Folder.
Really strange. I checked Folder-declarings multiple times.

Is there an example Provider Extension for FCE and Pages to download where it works?

Thank you and best regards,
Sören W.

**Comment by NamelessCoder** [comment]
There's a much longer explanation as to why that is, but the short version is that template files must always exist in the default template location and do not support overrides, because the metadata must be extracted before any TS context exists, thus only the native paths will work. Any rendering customisation you want to do, therefore has to be achieved with partials and layouts (which you can make dynamic if you wish).

You can overlay partial and layout root paths but they will only apply in FE and some contexts of BE.

PS: you should never put templates in `fileadmin/` even when overrides work. Storing them in an extension - which is what your provider extension was designed for - is always a better choice.

**Comment by soerenwach** [comment]
Thanks again for your helpfull response.
The thing is that I have two Websites on one TYPO3 Installation and I would like to use one Provider Extension and change the Paths on the root.
So I'll use a different Provider Extension for each Site now to make it work.

Thanks again and have a great day.
Sören W.

**Comment by NamelessCoder** [comment]
> So I'll use a different Provider Extension for each Site now to make it work.

That is exactly the right way of thinking about provider extensions ;)

Great day to you too!
